swiftlang/swift-corelibs-libdispatch

- configure.ac
Enable subdir-objects to silence warning caused by the addition
of linux_stubs.c to src/shims.  This seems like the most contained
fix to allow a .c file in the shims subdir without warnings.
> enable subdir-objects for automake

- INSTALL
Add some work in progress instructions to document current build instructions for Linux.
> Add some details on current build steps for Linux.

- configure.ac
- src/Makefile.am
If libdispatch is using functions found in libkqueue or
libpthread_workqueue, then we want libdispatch.so to
depend on those libraries so we don't have to specify
them explictly in the application linking command.
This change does that by adding KQUEUE_LIBS and
PTHREAD_WORKQUEUE_LIBS to the linking command for libdispatch.la
and exposing HAVE_PTHREAD_WORKQUEUE as a variable to automake.
> Propagate linker flags for kqueue and pthread_workqueue

- configure.ac
- tests/Makefile.am
- tests/bsdtestharness.c
- tests/bsdtests.c
- tests/bsdtests.h
- tests/bsdtestsummarize.c
- tests/dispatch_after.c
- tests/dispatch_apply.c
- tests/dispatch_cf_main.c
- tests/dispatch_concur.c
- tests/dispatch_data.c
- tests/dispatch_deadname.c
- tests/dispatch_drift.c
- tests/dispatch_group.c
- tests/dispatch_io.c
- tests/dispatch_io_net.c
- tests/dispatch_overcommit.c
- tests/dispatch_plusplus.cpp
- tests/dispatch_priority.c
- tests/dispatch_proc.c
- tests/dispatch_read2.c
- tests/dispatch_readsync.c
- tests/dispatch_starfish.c
- tests/dispatch_test.h
- tests/dispatch_timer_short.c
- tests/dispatch_vm.c
- tests/linux_port.h
Made an initial sweep through the test suite to resolve
the easy compilation issues.
Summary of changes:
(a) Guard mach specific code with #ifdef __APPLE__
(b) Changes to tests/Makefile.am to preserve
information from configure to guide test selection,
compilation, and execution.
(c) Map sysctlbyname calls to sysconf
(d) Simulate mach_absolute_time APIs
(e) Guard code using F_NOCACHE and F_GLOBAL_NOCACHE
(f) On Linux, simplify bsdtestharness.c to not use
libdispatch to execute the test cases (some of the
needed libdispatch functionality is not yet working).
To track progress, we broke the TESTS list in tests/Makefile.am
into UNPORTED_TESTS, PORTED_TESTS_FAILED, PORTED_TESTS_PASSED.
TESTS is defined as the union of PORTED_TESTS_PASSED and
PORTED_TESTS_FAILED.
If the automake testing …
> Port most of libdispatch tests to Linux (31 compile; 21 pass).

- src/internal.h
- src/semaphore.c
- src/time.c
add _dispatch_time_to_nanoseconds helper function to
encapsulate the conversion and use it in the two
places in semaphore.c where sem_timedwait is called.
fix enables dispatch_group test to pass
> posix sem_timedwait requires epoch-based timeout

- tests/dispatch_read2.c
The dispatch_read2 tests currently fail in two places due to the use of /dev/random as the source file. The issue in both cases is that the source file descriptor does not supply enough bytes of data to satisfy the read request from the test case.
On Darwin, /dev/random is the same as /dev/urandom, which provides a continuous stream of (pseudo)random data. On Linux, /dev/random provides limited data before blocking until more entropy is available.
Moving to /dev/urandom provides equivalent function on both Linux and Darwin and is the same as the existing use of /dev/random on Darwin.
> Switch to using /dev/urandom as file source

- tests/linux_port.h
The prototype for OSAtomicAdd32 is defined as:
```c
int32_t
OSAtomicAdd32(int32_t theAmount, volatile int32_t *theValue);
```
however the implementation in `linux_port.h` has the arguments inverted.
Correcting it doesn't cause any new tests to fail, but it required for fixing the dispatch_io tests (which I'm currently working on).
> Fix prototype for OSAtomicAdd32

- tests/dispatch_io.c
This PR fixes up the dispatch_io tests so that that pass. I've submitted this as a collection of commits as each fixes a different area. If you rather I squashed them, let me know.
* Add equivalent to immutable write test for Linux
There's currently a test that sets a directory as immutable, then runs a write test against it and checks that the write fails and the correct amount of data is still pending to write. As immutable isn't available in Linux, I've replaced this with setting the directory as non-writeable (and retaining the use of immutable on Mac OS).
* Limit data read in to the size of the file
The IO read/write test reads in 1024 * 1024 bytes of data from `/usr/share/dict/words` however there isn't necessarily that much data available (there isn't on my Linux install), so I've …
> Fix up dispatch_io tests

- src/init.c
Three of the tests are failing because the `DISPATCH_QUEUE_CONCURRENT` structure hasn't been initialised (the value for `DISPATCH_QUEUE_CONCURRENT->do_vtable` is `NULL`.
This is occurring because `DISPATCH_QUEUE_CONCURRENT` is aliased to `_dispatch_queue_attrs` in `xcodeconf/libdispatch.aliases`, but aliasing (the use of the `-alias_list` linker option) is only supported on Darwin.
Up until libdispatch-4xx, `DISPATCH_QUEUE_CONCURRENT` was initialised explicitly in init.c. Taking that approach for non-Apple platforms certainly solves the issue, but there may be a better approach to doing the equivalent of aliasing on Linux.
> Initialise dispatch_queue_attr_concurrent on Linux

- tests/Makefile.am
Cleanup the test status in Makefile.am by moving the following now passing tests from `PORTED_TESTS_FAILED` to `PORTED_TESTS_PASSED`:
```dispatch_group
dispatch_concur
dispatch_context_for_key
dispatch_read
dispatch_read2
dispatch_readsync
dispatch_io
dispatch_io_net
```
And add `dispatch_select` to the makefile by moving it from `UNPORTED_TESTS` to `PORTED_TESTS_PASSED`.
The output of check-TESTS should now be:
```
===========================================
2 of 32 tests failed
Please report to libdispatch@macosforge.org
===========================================
```
with `dispatch_priority` and `dispatch_priority2` as the two failing ported tests.
> Cleanup test status

- src/semaphore.c
Code was not properly handling a return code of 0 from sem_timedwait
(it would interpret it as a timeout).  Change logic of test to match
that used after the other call to sem_timedwait in this file.
> Bug fix in testing of return code of sem_timedwait

- configure.ac
Need to look in $srcdir for libpwq to support configure
being run in another directory (ie, when run by build-script).
> Fix for libpwq test when running configure externally

- src/io.c
Reusing the base structure of the function to maintain the offset logic
and replace fcntl( F_RDAVICE ) with readahead under linux.
> Support for file readahead under linux using readahead

- tests/.gitignore
- tests/Makefile.am
Update grouping of passing/failing tests to represent current
status and to match orginal order of test cases (avoids running
test_select first, which takes a long time).
Also update tests/.gitignore with additional generated files
> Update lists of passing/failing tests in Makefile.am for Linux

- configure.ac
- tests/Makefile.am
Two small fixes needed to enable build/test to happen
in an external directory (for example when building
libdispatch under the control of swift/utils/build-script).
> autotools fixes for build/test outside src dir

- src/Makefile.am
- tests/Makefile.am
Small fixes to (a) use proper paths to libpwq when building
out-of-tree and (b) include tests/linux_port.h in list of
test sources (needed for distcheck).  With these changes
'make distcheck' works as expected.
> SR-438: 'make distcheck' fails for libdispatch on Linux

- configure.ac
- src/.gitignore
- src/Makefile.am
- src/swift/Dispatch.swift
- src/swift/module.map.in
- src/swift/swift_wrappers.c
This commit adds a src/swift directory that contains
Dispatch.swift and Dispatch.c (based on existing files in
swift/stdlib/public/SDK/Dispatch) and a module.map.in template.
We made some initial changes to Dispatch.swift and Dispatch.c to
adapt them to Linux by dropping MACH API functions/adapters.
The libdispatch build process is extended to include Dispatch.o
in libdispatch.so and to generate Dispatch.swiftmodule,
Dispatch.swiftdoc and a module.map file when configure is
given a --with-swift-sdk argument.
Swift programs that import Dispatch can be compiled, linked,
and run against the generated files, but must include some
extra command line arguments due to the use of @convention(block)
to bridge from Swift blocks to the -fblocks expected by dispatch.
In particular, the following …
> Initial integration of Swift overlay into libdispatch build

- dispatch/Makefile.am
- dispatch/module.map
- man/Makefile.am
- os/Makefile.am
- src/Makefile.am
Simplify the build/install logic for the Swift overlay portion of
libdispatch to assume that if the Swift overlay is being built
then the intended install target is a Swift toolchain.
In conjunction with the change to swift/utils/build-script-impl
in https://github.com/apple/swift/pull/1212, this change enables Swift programs compiled using
the resulting built toolchain to successfully import
Dispatch with only -Xcc -fblocks as extra arguments to swiftc
(no longer need to also specify -I<path-to-dispatch-module>).
> if building Swift overlay, install into Swift toolchain dir structure

- .gitmodules
- configure.ac
Switch to mheily repository (all the needed changes from
dgrove-oss have been merged upstream). Tweak libdispatch's
configure.ac so that if we are building our own libpwq
from source, the primary configure passes down an argument to
libpwq's configure to modify libpwq's install targets
so that libpthread_workqueue.la is built as a libtool
convenience library and libpwg's man pages and header
files are not installed when libdispatch is installed.
> Switch libpwq submodule to upstream repository

- tests/.gitignore
- tests/Makefile.am
The parallel test harness automatically puts test output into log files, 
summarizes the logs, and produces nicer (1 line per test) output to
stdout when running the tests.
> Switch to using automake parallel test harness

- tests/Makefile.am
For Swift CI integration it is desirable to have a target
specifically to build the test cases and test utility programs.
> Add build-tests target to build tests separately from make-check

- src/init.c
- src/io.c
- src/semaphore.c
- src/source.c
- tests/bsdtestharness.c
- tests/bsdtests.c
- tests/dispatch_overcommit.c
- tests/dispatch_starfish.c
- tests/dispatch_timer.c
Resolve all compiler warnings when building libdispatch and
the test suite on linux.  It now compiles cleanly.
Many of the warnings were due to platform-specific sized integers
being used in printf-like contexts.  In libdispatch itself, I took
the approach of adding casts to the values to match the size/type
specified in the printf format string (under the assumption that
the expected output format should not be changed and needs to be
the same on all platforms).
> resolve all compiler warnings

- src/semaphore.c
Before waiting on a dispatch_semaphore (slow path), notify the thread pool manager
that this thread will go to block.
Depends on the small patch submitted to libpwq which has been integrated. 
This patch will wakeup the thread manager (instead of doing this once per second)
which then forces a new worker_thread to be started.
Lack of this patch will result in reduced concurrency at program startup time.
See https://bugs.swift.org/browse/SR-761 for some symptoms.
This patch is not a fix for all, for instance it does not catch sleep() calls, but according
to Swift Foundation implementers its a good intermediate solution before the  linux kernel solution
is considered which has a longer lead time and requires a kernel extension to be installed.
> inform libpwq thread manager before semaphore wait

- configure.ac
Setting a configure variable that is tested in
a later AM_CONDITIOANL to true, is not the same as
setting it to true
> Another fix for libpwq configuration

- dispatch/dispatch.h
With the 03242016 development drop, building the
Dispatch overlay on Linux fails because mode_t and
off_t are not defined.  This is a minimal fix to
include the needed header files and get the build
working again.
> Build fix for Linux overlay with 03242016 compiler.

- tests/dispatch_apply.c
We need to adjust the code speed on Linux S/390 to keep the busy thread running.  Otherwise the test would fail.
> Adjust code speed when running on s390x

- private/queue_private.h
- src/Makefile.am
- src/internal.h
- src/queue.c
- src/shims.h
- src/shims/pthread_main_np.h
Equivalent to PR #46 but to bring the changes into the 'experimental/foundation' working branch.
This opens up two APIs for use by CFRunLoop in Foundation:
```
dispatch_get_main_queue_eventfd_4CF()
dispatch_main_queue_drain_4CF()
```
> Add support for CFRunLoop integration APIs

- src/Makefile.am
- src/block.cpp
- src/shims/linux_stubs.c
Add block.cpp to libdispatch_la_SOURCES when !USE_OBJC
Tweak linker hack for DISPATCH_BLOCK_SPECIAL_INVOKE to work on linux
Remove stub implementation of dispatch_create_block (porting remnant).
> Enable dispatch_block_create for Linux

- src/inline_internal.h
- src/queue.c
- src/source.c
Avoid using an expression whose type is a bitfield in
macros like slowpath or dispatch_assert that internally
use typeof on their argument expression.
> SR-1101 : clang 3.9 doesn't allow typeof on bit-field

- configure.ac
- dispatch/dispatch.h
- os/linux_base.h
- os/voucher_private.h
- src/firehose/firehose_internal.h
- src/init.c
- src/inline_internal.h
- src/internal.h
- src/object.c
- src/object_internal.h
- src/queue.c
- src/semaphore.c
- src/shims.h
- src/shims/linux_stubs.h
- src/shims/lock.c
- src/shims/lock.h
- src/source.c
- src/voucher_internal.h
Minimal set of changes to get sources merged
from libdispatch-685 to compile and run on Linux.
> Linux port of libdispatch-685 merge

- tests/dispatch_concur.c
Adjust pass/fail criteria to allow some divergence
when the level of expected concurrency is greater
than the number of hardware CPUs on the system on
which the test is being run.
> Adjust pass/fail criteria in dispatch_concur

- tests/dispatch_io.c
Test was failing because number of bytes read overflows int32_t.
Changing to a uint32_t is sufficient to avoid overflow.
Changing to int64_t would also work, but is a larger change (since
we then need to provide an OSAtomicAdd64 function on Linux).
> avoid overflow in dispatch_io test

- configure.ac
- src/internal.h
- src/shims/linux_stubs.c
config.h is generated by the autotools build process.
Having it stored in git causes useless diffs and the
need for git checkout operations when rebasing because
the generated version differs from the version in git.
> Avoid overwriting config.h with generated header

- src/data.c
- src/init.c
- src/queue.c
- src/shims/linux_stubs.c
- src/shims/linux_stubs.h
guard stray usage of mach_task_self with #if HAVE_MACH
and remove mach_test_self() from linux_stubs.
> eliminate mach_task_self from linux_stubs

- configure.ac
- src/init.c
- src/queue.c
- src/shims/linux_stubs.c
- src/shims/lock.h
- src/shims/tsd.h
Bring up previous patch for Thread Local Storage utilization over explicit keys to 685 base.
> TLS: Thread Local Storage 

- tests/Makefile.am
The following tests are sometimes failing when run under `make check-TESTS`:
```
dispatch_apply
dispatch_group
dispatch_concur		
dispatch_timer_short		
dispatch_sema			
dispatch_drift
```
All are intermittent, and some of these can hang (e.g. `dispatch_group` and `dispatch_sema`), so we can't just move them to the XFAIL list.
> Disable intermittently failing tests

- tests/Makefile.am
Running the dispatch tests with the Swift overlay complied in fails because the tests can't link to libswiftCore.so at runtime.
The quick fix for this is to add an `rpath` to the `SWIFT_RUNTIME_LIBS` directory which contains the libswiftCore.so from the version of Swift used to compile the overlay.
> Add rpath for libswiftCore when building with the Swift overlay

- tests/Makefile.am
The dispatch_readsync test is failing in the Swift CI, so temporarily moving to the FAILING_TESTS list until we understand why.
> Disable dispatch_readsync test as it fails in Swift CI

- tests/dispatch_apply.c
The dispatch_apply test sometimes fails in multicore machines.  The
failed function is test_apply_contended which tests if dispatch_apply
can make progress and finish with N concurrent busy threads running,
where N is the number of CPUs.  According to the testing log, it fails
because some busy threads already finish before dispatch_apply() is
invoked.
This happens because the test uses the ITERS_PER_SECOND variable to
control the number of iteration of the loop in the busy thread and
optimistically __hope__ the execution time is long enough to complete
the test. But sometimes this hope fails when the testing machine has
greater computing power and more CPU cores.
Instead of using ITERS_PER_SECOND, which makes an assumption about the
computing power of the test machine, a condition …
> Use a condition variable to control busy threads in dispatch_apply test

- tests/Makefile.am
Disable another 3 tests with intermittent failures in the CI. These are:
- dispatch_read2: the problem is likely an overflow where the `usr/lib` directory is large. This is fixed in master already
- dispatch_io: the test triggers 7 events which have to execute within an arbitrary time limit of 3 seconds. This doesn't fail for me locally, but the events often take 2 seconds, so likely this time limit just needs to be extended.
- dispatch_read2: not sure why this is failing, but it seems to roughly 1 time in 20.
We'll need to fix up the tests properly in the future, or create new alternative tests, but at the moment this PR is to disable them so that we don't have build failures.
> Disable tests failing intermittently in Swift CI

- configure.ac
- dispatch/Makefile.am
- dispatch/module.map
- dispatch/module.modulemap
- src/Makefile.am
- src/data.c
- src/swift/Block.swift
- src/swift/Data.swift
- src/swift/Dispatch.swift
- src/swift/DispatchStubs.cc
- src/swift/IO.swift
- src/swift/Private.swift
- src/swift/Queue.swift
- src/swift/Source.swift
- src/swift/Time.swift
- src/swift/Wrapper.swift
- tests/Makefile.am
A useful checkpoint along the way to a complete implementation of
the Swift3 overlay for libdispatch on non-Objective C platforms.
The overlay code builds successfully and simple example programs
using queues and timers work as expected.
The basic approach is to wrap the C libdispatch objects in Swift
objects and make the C dispatch APIs available internally via the
CDispatch module.
A few pieces (marked with FIXME) are ifdefed out to avoid compilation
problems (will get back to them in later commits) or still need to
be implemented (release on deinit).
Although the installed libdispatch can be used in Swift programs via
'import Dispatch', the swiftc command for the client program currently
needs to pass additional command line flags (to be fixed later). For example:
swiftc -Xcc -fblocks …
> Initial Swift3 wrapping overlay for libdispatch

- src/swift/DispatchStubs.cc
- src/swift/Wrapper.swift
ARC support in wrapping overlay. Add deinit methods to wrapping
Swift classes that call dispatch_release on the wrapped C objects.
> release wrapped C objects when Swift object deinitialized

- src/queue.c
If the main thread calls pthread_exit on Linux, the process
becomes a zombie. Modify dispatch_main to avoid this by manually
performing thread cleanup and pausing the thread instead of calling
pthread_exit.  This is an updated version of an old patch for this
issue (https://lists.macosforge.org/pipermail/libdispatch-dev/2011-May/000522.html).
> Linux: avoid zombie process when dispatch_main is called

- private/private.h
- src/internal.h
- src/queue.c
- src/shims/linux_stubs.c
Here's a first cut at this.   It compiles, but I haven't actually tested it with foundation yet.  Implementation mostly based on the code from experimental/foundation, but I decided to more closely mirror the mach code and stash the eventfd in dq->do_ctxt instead of introducing a static variable just for the main queue. 
I'm not that happy with the HANDLE (windows) vs. int (linux) aspect of the patch.  I partially introduced dispatch_handle_t, but I also should introduce a symbolic constant for 0/NULL and be more careful in the linux-specific code to always use dispatch_handle_t instead of int.  Do we want dispatch_handle_t or similar?  On as similar note, we could define dispatch_handle_t to be mach_port_t if TARGET_OS_MAC and if we could change the name of …
> Enable CF runloop support for linux

- tests/Makefile.am
The libdispatch CI test failed for #100:
https://github.com/apple/swift-corelibs-libdispatch/pull/100
Due to the following linkage issues when building the tests:
```
../src/.libs/libdispatch.so: undefined reference to `_TTSgq5SiSis10ComparablesSis11_Strideables___TFVs14CountableRangeg8endIndexx'
../src/.libs/libdispatch.so: undefined reference to `_TTSgq5SiSis10ComparablesSis11_Strideables___TFVs14CountableRangeg10startIndexx'
../src/.libs/libdispatch.so: undefined reference to `_TTSgq5SiSis10ComparablesSis11_Strideables___TFVs14CountableRangeCfT15uncheckedBoundsT5lowerx5upperx__GS_x_'
```
Those symbols appear in libswiftSwiftOnoneSupport. Additionally after adding that library to the linkage flags, the tests fail to find the Swift libraries during test execution, which can be fixed by …
> Link to Swift libraries for CI tests

- src/swift/DispatchStubs.cc
resolve FIXME left in initial Swift3 port to Linux by replicating
definition of SWIFT_CC(swift) from swift/include/Runtime/Config.h.
> define SWIFT_CC(swift) macro for DispatchStubs

- configure.ac
- src/Makefile.am
- src/internal.h
- src/source.c
Add a command line option to allow selecting a build variant
(debug, release, releaseassert, releasedebuginfo). If no variant
is selected, default to release.
Also two small fixes to compilation errors in code guarded by
DISPATCH_DEBUG to allow the debug and releaseassert variants
to build successfully.
> autoconf support for selecting build variant

- src/shims/linux_stubs.h
- src/source.c
This modification takes advantage of the kevent timer granularity extension 
https://github.com/mheily/libkqueue/pull/14 , that was already merged.
This fixes some of the timer resolution and performance issues.
> leverage of new kevent timer granularity functionality

- src/swift/Data.swift
If you try to create an iterator from an empty DispatchData, it crashes due to force-unwrapping a nil pointer.
> [Data] fix crash when creating iterator of empty DispatchData

- src/swift/Data.swift
- src/swift/IO.swift
- src/swift/Wrapper.swift
Deallocation / reference counting support for DispatchData
in the wrapping overlay consisting of two main pieces.
First, since DispatchData is a struct and dispatch_data_t is
a COpaquePointer, we need an intermediate class __DispatchData
on which to perform the reference counting operations to enable
the backing _dispatch_data_t to be deallocated when they are no
longer reachable.  I overlooked the mapping of _dispatch_data_t
to OS_dispatch_data in Dispatch.apinotes in my initial pull request
for the wrapping overlay and as a result all the dispatch_data_t
instances were not being reference counted.
Second, enable the DispatchData.Deallocator portion of the API.
After some experimentation, found a way to have the desired API
without getting a reference to _TMBO in the generated code.
Left …
> deallocation support for DispatchData on Linux

- src/swift/Wrapper.swift
dispatch_main is meant to be made available via
the global function dispatchMain().
> add dispatchMain to wrapping overlay

- src/source.c
Should have used an ifdef instead of an if to guard this block
of code.  Fixes compilation on linux when using an older version
of libkqueue that doesn't include the nsec kevent support.
> fix compilation error when building against old libkqueue

- tests/Makefile.am
Move the following tests to the XFAIL list as they fail in the Swift CI environment:
- `dispatch_concur`: fails every time
- `dispatch_readsync`: fails around 50% of the time
The failures can be recreated on a sufficiently large (24 CPU+) machine locally, so we can debug offline and re-enable the tests once we've either fixed the test or an underlying issue in dispatch/kqueue/pwq
Disabling the tests should allows us to get the CI environment running clean, and moving towards enabling higher level testing by integrating into Foundation.
Note that `dispatch_concur` still fails for me locally with PR #117 applied, although that patch certainly causes many less components of the test to fail.
> Move dispatch_concur and dispatch_readsync to the XFAIL list

- tests/dispatch_concur.c
Further relax the expected minimum level of concurrency
when running on a multi-CPU system to only require that
we observe at least 50% of the potential concurrency is
actually realized.  This should be loose enough to avoid
spurious failures when run in the CI environment while
still being able to detect when we are very badly missing
the expected levels of concurrency.
> relax passing conditions for dispatch_concur

- tests/dispatch_timer_short.c
Reduce N (number of suspended timers) from 100000 to 25000
to make it suitable for running in CI environment.
Test case execution time on Linux appears to be roughly quadratic
in N.  Setting N to 25000 yields a test that runs in about 30
seconds; at 100000 the test takes around 15 minutes to run.
Profiling says that 99% of test execution is spent in
_dispatch_timers_update.
> adjust dispatch_timer_short to control testing time

- src/swift/Data.swift
- src/swift/Private.swift
- src/swift/Queue.swift
Unsafe[Mutable]Pointer<Void> is replaced by Unsafe[Mutable]RawPointer.
Migrating often means simply removing casts to/from UnsafePointer<UInt8>
and working directly with UnsafeRawPointer instead.
Unfortunately some API's, like NSData still want UnsafePointer<UInt8>,
which requires "binding" memory to UInt8 before passing it to the API.
> Update for SE-0107: Migrate Void->Raw.

- src/swift/Block.swift
- src/swift/Data.swift
- src/swift/Dispatch.swift
- src/swift/IO.swift
- src/swift/Queue.swift
- src/swift/Source.swift
- src/swift/Time.swift
- src/swift/Wrapper.swift
- tests/Makefile.am
First cut at pulling in the recent Swift overlay changes and get them
building on Linux.
> [overlay-syncup] sync overlay changes to Linux

- INSTALL
Add description for building libdispatch with Swift API
either as part of building a Swift toolchain from source
using utils/build-script or using a pre-built Swift toolchain.
Update Linux-specific instructions to try to avoid some
common problems people have been reporting.
> Update INSTALL instructions

- src/swift/Data.swift
- src/swift/Queue.swift
- src/swift/Time.swift
Without this change, the overlay fails to compile when running Swift's `utils/build-script --libdispatch` as of apple/swift@805e06e, which landed earlier today.
> fix issues preventing overlay from compiling due to SE-0025

- src/swift/Data.swift
Depends on https://github.com/apple/swift/pull/3854
[SE-0101](https://github.com/apple/swift-evolution/blob/master/proposals/0101-standardizing-sizeof-naming.md) removes `sizeof`, `sizeofValue` and related functions from the stdlib.
This PR is migrating them to newly introduced `MemoryLayout<T>` values.
> [SE-0101] Migration

- src/swift/Block.swift
- src/swift/Dispatch.swift
- src/swift/IO.swift
- src/swift/Queue.swift
- src/swift/Wrapper.swift
[SE-0103][1] makes `@noescape` the default annotation for blocks, adding the `@escaping` annotation in return to specify the opposite behaviour.
This changeset adds the annotation as it was required by the compiler.
[1]: https://github.com/apple/swift-evolution/blob/master/proposals/0103-make-noescape-default.md
> [SE-0103][noescape by default] Migration to @noescape by default feature.

- tests/Makefile.am
As discussed in PR #133, we strongly suspect that the test is at fault. Unfortunately we can only reproduce this intermittently in the CI environment, which we need to get running clean to progress the integration of libdispatch into the Swift toolchain.
Disabling the test for now, and we can work on re-integrating it and resolving the issues using the PR test builds in the future.
> Disable dispatch_read2 due to intermittent failure

- INSTALL.md
- README.md
- dispatch/module.modulemap
- m4/blocks.m4
- src/BlocksRuntime/Block.h
- src/BlocksRuntime/Block_private.h
- src/BlocksRuntime/data.c
- src/BlocksRuntime/runtime.c
- src/Makefile.am
- tests/Makefile.am
held github wrong in #145 and merged to the wrong branch...
> Really backport PRs 134 135 139 138 140 to swift-3.0-branch

- tests/dispatch_io.c
- tests/dispatch_io_net.c
- tests/dispatch_read.c
- tests/dispatch_read2.c
- tests/dispatch_select.c
> use /usr/bin/vi instead of /usr/share/dict/words as test input 

- tests/Makefile.am
> [Swift 3.0] Disable drift, pingpong and io tests to clean up Swift CI

- tests/Makefile.am
We're still getting some intermitted failures in the Swift CI which we've not been able to recreate locally (on a 38-way machine).
These are in:
* `dispatch_pingpong` - this results in a hang
* `dispatch_drift` - this fails because we exceed the drift threshold
Additionally, `dispatch_io` always fails in the CI builds on Ubuntu 14.04 where it runs out of file descriptors. I've run the tests on Ubuntu 14.04 and and 15.10 locally, and can't find any evidence that we're leaking file descriptors - it looks like the Swift CI's hard limit for NOFILES is too low.
In order to clean up the CI quickly, I'm proposing that we disable all three tests. We can then fix the CIs configuration and debug the tests once we've got Swift 3.0 done.
> Disable drift, pingpong and io tests to clean up Swift CI

- tests/Makefile.am
Temporarily disable the `dispatch_cascade` test as it hung in the Swift CI with the following log:
```
==================================================
[TEST] Dispatch Cascade
[PID] 19223
==================================================
[BEGIN] Process exited
Actual: 1
Expected: 0
[FAIL] Process exited (bsdtestharness.c:132)
bsdtestharness.c:132
[PERF]  wall time: 0.034725
[PERF]  user time: 0.056000
[PERF]  system time: 0.008000
[PERF]  max resident set size: 17660
[PERF]  page faults: 0
[PERF]  swaps: 0
[PERF]  voluntary context switches: 43
[PERF]  involuntary context switches: 10
FAIL dispatch_cascade (exit status: 1)
``` 
Note that the process exited because the CI job killed it after 45 minutes.
> Disable dispatch_cascade due to hang in Swift CI

- src/swift/Block.swift
- src/swift/Queue.swift
Remove temporary APIs from Linux Dispatch overlay;
swift-corelibs-foundation builds without them and
they are not present in the Darwin Dispatch overlay.
> SR-2356 : Remove temporary APIs from Linux overlay

- src/swift/Block.swift
- src/swift/Queue.swift
Remove temporary APIs from Linux Dispatch overlay;
swift-corelibs-foundation builds without them and
they are not present in the Darwin Dispatch overlay.
> [Swift3] SR-2356 : Remove temporary APIs from Linux overlay

- tests/dispatch_io.c
- tests/dispatch_io_net.c
- tests/dispatch_read.c
- tests/dispatch_read2.c
- tests/dispatch_select.c
Pulls #151 "use /usr/bin/vi instead of /usr/share/dict/words as test input" into the Swift 3 branch. Although this change is not strictly required for branching swift-corelibs-foundation for Swift 3, this keeps all tests passing, which will help smooth out the integration.
Not to be merged until similar changes are ready to land for [swift #4528](https://github.com/apple/swift/pull/4528), [swiftpm #617](https://github.com/apple/swift-package-manager/pull/617), and [swift-corelibs-xctest #170](https://github.com/apple/swift-corelibs-xctest/pull/170).
> [DO NOT MERGE YET] Cherry-picks aed3841 for swift-3.0-branch Foundation integration

- configure.ac
- dispatch/dispatch.h
- src/io.c
This patch enables compilation from build-script on armv7.  I don't expect this patch to be without controversy; rather I'd like this to be the opening point for some discussion about the specific implementation.
In particular, I'd like to draw attention to this PR at foundation: https://github.com/apple/swift-corelibs-foundation/pull/399/files which addresses val_list in the same way as presented here.
Furthermore, PAGE_SIZE is, for some reason, undefined on ARM.  The definition provided here is an assumption, and kind of a hack.  I'd happy to receive some guidance whether there is a better way to move forward.
Thanks!
> Fix building on armv7

- src/io.c
POSIX.1-2001 allows either EAGAIN or EWOULDBLOCK to be returned when a
write to a nonblocking socket would block. For example IBM z/OS returns
EWOULDBLOCK for this case.
> handle EWOULDBLOCK error in _dispatch_operation_perform

- src/swift/Private.swift
Apply changes from 25f7cda01c324f13995ae2d1c54c8d2b0615ea36
to the copy of Private.swift used by the wrapping overlay.
This reduces divergence from Darwin overlay.
> [libdispatch-fixits] Address stale or incorrect fixits

- src/swift/Queue.swift
Replicate 6fe9b13f12fc34d80c8c63cce84fa3667424baaf which fixes
SR-2248 from the Darwin overlay to the wrapping overlay.
> Add fast path for queue.async(flags: .barrier)

- src/swift/Block.swift
- src/swift/Data.swift
- src/swift/Wrapper.swift
A collection of small fixes to eliminate needless
differences (as reported by diff -r -b) between
swift/stdlib/public/SDK/Dispatch and
swift-corelibs-libdispatch/src/swift.
> Fix some small divergences from Darwin overlay

- src/swift/IO.swift
- src/swift/Source.swift
- src/swift/Time.swift
Replicate e32016ffd765020c696bc5d1e42606074305f2db
from the Darwin overlay to the wrapping overlay.
> Correct signedness handling of DispatchTimeInterval

- src/swift/Wrapper.swift
DispatchIO should not have an internal init(dispatch_queue_t)
that stores a dispatch_queue_t into a field of type dispatch_io_t.
Bug is only in the wrapping (Linux) overlay; not in Dispatch.apinotes.
> remove unused/incorrect internal init from DispatchIO

- src/swift/Data.swift
- src/swift/IO.swift
- src/swift/Wrapper.swift
Fixes an over-release problem in the wrapping overlay that
occurred in callback blocks that take DispatchData structs.
Just going through the glue layer between the Swift and C APIs
should not result in a net change in the reference count of
the dispatch_data_t object that the CDispatch layer is giving
us to hand to the Swift callback block.  However, when the
temporary DispatchData struct we created in the wrapping layer
(and its wrapped __DispatchData object) went out of scope at
the end of the callback, the dispatch_data_t was released
by __DispatchData's deinit resulting in an unintended net -1
from the glue code.
We either need to add a compensating retain before entering the
callback block or suppress the release in the deinit. This patch
suppresses the release by adding an internal …
> SR-2656:  extra releases of dispatch_data_t objects on Linux

- src/Makefile.am
Detect that swiftc has changed since the Swift file has
been compiled and force it to be recompiled.  The explicit
rm of the target before regenerating it is needed because if
the new compiler generates exactly the same bits as the old
one the .o file isn't updated and the target gets stuck as
being out-of-date.  An explicit rm avoids that problem.
> Add dependency on swiftc for %.o.%.swift rules

- _posts/2010-05-14-apache-mpm-sample-code.md
Fixes the `curl` commands by instructing it to follow HTTP redirects.
> Follow HTTP redirects

- tests/dispatch_timer_set_time.c
Adjust the number of 'fast' ticks and the timeout
parameters to make the test much less likely to
be subject to spurious failures in the CI environment.
> SR-2856: adapt dispatch_timer_set_time for CI

- src/Makefile.am
Detect that swiftc has changed since the Swift file has
been compiled and force it to be recompiled.  The explicit
rm of the target before regenerating it is needed because if
the new compiler generates exactly the same bits as the old
one the .o file isn't updated and the target gets stuck as
being out-of-date.  An explicit rm avoids that problem.
> Swift3: Add dependency on swiftc for %.o.%.swift rules

- configure.ac
- tests/Makefile.am
Add a configure argument to enable extended test suite.
The extended test suite is disabled by default (and thus
will not be run in vanilla Swift CI jobs).
Move yet another intermittently failing test,
dispatch_suspend_timer, out of the list of default tests.
> configure support for extended test suite

- configure.ac
- tests/Makefile.am
Add a configure argument to enable extended test suite.
The extended test suite is disabled by default (and thus
will not be run in vanilla Swift CI jobs).
Move yet another intermittently failing test,
dispatch_suspend_timer, out of the list of default tests.
> Swift 3: configure support for extended test suite

- src/swift/Data.swift
- src/swift/DispatchStubs.cc
To avoid leaking the block parameter of enumerateBytes,
we need to directly call CDispatch.dispatch_data_apply
(not _swift_dispatch_data_apply). However, we need to tell
the compiler that the internal closure that translates between
the C and Swift layers will not cause the captured block
parameter to escape.  If SR-2313 were implemented, we could use
withoutActuallyEscaping.  Since withoutActuallyEscaping is not available,
we instead use unsafeBitCast to bypass the compiler's analysis.
> Swift3: SR-3002: DispatchData.enumerateBytes on Linux leaks the block

- src/Makefile.am
Simplify the rules for compiling .swift source files when
building the wrapping overlay to avoid invoking the swiftc
front-end directly.  This avoids using an unsupported
swift compiler command line API and does the compilation
in a single shot with whole-module-optimization (potential
for better generated code).
> Avoid invoking swiftc -front-end when building Dispatch overlay

- Makefile.am
- configure.ac
- src/Makefile.am
- src/internal.h
- src/queue.c
- src/shims.h
- src/shims/android_stubs.h
- src/shims/getprogname.h
- src/shims/linux_stubs.c
- src/shims/linux_stubs.h
- src/shims/lock.c
- src/source.c
- src/swift/Source.swift
- src/swift/Wrapper.swift
- tests/Foundation/bench.mm
- tests/dispatch_apply.c
- tests/dispatch_concur.c
- tests/dispatch_priority.c
- tests/dispatch_readsync.c
- tests/dispatch_vm.c
This changeset adds support for Android cross-compilation with the same restrictions applied to `swift` project.
- `--disable-build-tests`: tests are failing to be built due to the lack of `spawn`. Until this is fixed, the flag will be useful to complete compilation
- `--with-android-ndk`: Android NDK path to be used as a base for cross toolchain, SDK and support files.
- `--with-android-ndk-gcc-version`: NDK GCC version to be used (defaults to `4.9`)
- `--with-android-api-level`: API version to be used for compilation
- `--enable-android`: Enabled Android cross-compilation. In this implementation, as it is being done right now in `swift`, this is enforcing `arm-linux-androideabi` `armeabi-v7a`. 
There are a few things in this changeset that I'd like to iterate, assuming there are better …
> Android support

- src/swift/Data.swift
- src/swift/DispatchStubs.cc
To avoid leaking the block parameter of enumerateBytes,
we need to directly call CDispatch.dispatch_data_apply
(not _swift_dispatch_data_apply). However, we need to tell
the compiler that the internal closure that translates between
the C and Swift layers will not cause the captured block
parameter to escape.  If SR-2313 were implemented, we could use
withoutActuallyEscaping.  Since withoutActuallyEscaping is not available,
we instead use unsafeBitCast to bypass the compiler's analysis.
> SR-3002: DispatchData.enumerateBytes on Linux leaks the block

- src/swift/DispatchStubs.cc
Swift3 branch of #193 as requested by @gparker42
> Swift3: Fix libdispatch's copy of objc_retainAutoreleasedReturnValue.

- README.md
- TESTING.md
Add brief documentation on how to run tests
and note assumption that /usr/bin/vi is present
to use as input for IO test cases.
> SR-3237: Document libdispatch testsuite

- configure.ac
- src/Makefile.am
Two different issues were affecting the use and generation of output directories for libraries.
* os_string wasn't resolving `android` for the `linux-androideabi` target OS
* Installation directory for cross-compiled target is malformed.
To fix the latter, I'm now passing `OS_STRING` and using `host_cpu` instead of `build_cpu`.
> os_string fixes for cross-compilation and Android when Swift is enabled

- src/swift/Data.swift
Now that withoutActuallyEscaping is implemented, use it instead
of unsafeBitCast to allow passing a closure capturing a non-escaping
block down to the C implementation of dispatch_data_apply (which does
not actually escape its block argument).
> SR-3477: replace unsafeBitCast by withoutActuallyEscaping

- src/shims/hw_config.h
If pthread_getaffinity_np is available, then use the cpuset
of the current thread to determine the number of active cpus.
> consider affinity when computing active cpus on Linux

- src/swift/DispatchStubs.cc
- src/swift/Wrapper.swift
In `DispatchIO.read`, the `dispatch_data_t` object received from `dispatch_io_read` will be released once the block passed to `dispatch_io_read` returns.
In the Swift overlay (`src/swift/IO.swift`) the code marks that data object correctly as "borrowedData"
public func read(offset: off_t, length: Int, queue: DispatchQueue, ioHandler: @escaping (_ done: Bool, _ data: DispatchData?, _ error: Int32) -> Void) {
dispatch_io_read(self.__wrapped, offset, length, queue.__wrapped) { (done: Bool, data: dispatch_data_t?, error: Int32) in
ioHandler(done, data.flatMap { DispatchData(borrowedData: $0) }, error)
}
}
that however leads to use-after-frees if the Swift `DispatchData` is kept around for longer.
The change I made will `retain` the underlying `dispatch_data_t` if it's "borrowed" which I …
> don't hold references to unowned DispatchData objects (SR-3628)

- src/swift/DispatchStubs.cc
- src/swift/Wrapper.swift
(cherry picked from commit dac881a0ec3e41b669aac1f2d686e90e665f08ae)
> don't hold references to unowned DispatchData objects (SR-3628) for Swift 3.1

- src/swift/Time.swift
... for the cases where seconds parameter is NaN or infinite.
rdar://problem/29764171
Similar to https://github.com/apple/swift/pull/6961
> Fix + and - operations on DispatchTime and DispatchWallTime

- src/swift/Private.swift
The same change was already made in the swift repo (https://github.com/apple/swift/pull/6958)
rdar://problem/27915073
> Correct the Xcode fixits for dispatch_async() and dispatch_group_async()

- src/swift/Time.swift
The documentation does not make it clear that DispatchTime(uptimeNanoseconds: 0) produces a value that represents the current nanoseconds since boot, not the time of boot. The fix adds a documentation comment to that effect.
(Radar 28814085)
Resolves [SR-2807](https://bugs.swift.org/browse/SR-2807).
> Adding documentation to clarify the result of DispatchTime(uptimeNanoseconds: 0) 

- src/BlocksRuntime/runtime.c
- src/Makefile.am
When compiling on non-Apple platforms, this removes ObjC support functions that are not needed which allows removal of ```libdl```.
Hopefully I have used the correct flags, ```HAVE_OBJC``` in the code and ```USE_OBJC``` in the makefile but if there are better flags to use please let me know.
I tested this by building the static library ```libdispatch.a``` and linking it into a statically built swift program which included ```import Dispatch``` and didnt see any missing references so the functions that have been excluded should be correct.
> Remove ObjC support functions not needed on non-ObjC platforms

- os/linux_base.h
The include of sys/user.h is not needed; it
is a leftover from the initial linux port.
Eliminating it avoids a build problem for
the Swift dispatch overlay on ubuntu 14.04
powerpc64le because the content of sys/user.h
confuses the clang module importer when it
attempts to import CDispatch.
> Remove unused include of sys/user.h

- src/Makefile.am
The static version (`libdispatch.a`) that can be compiled using
`./configure --enable static=yes` was missing all the Swift overlay symbols
(everything in `swift_overlay.o`). The reason for that is that the linker is
invoked through libtool which wants `.lo` files but the Swift overlay got passed
as a `.o` file. This first of all leads to this warning:
*** Warning: Linking the shared library libdispatch.la against the non-libtool
*** objects [...]/swift_overlay.o is not portable!
And the result is that libtool doesn't include `swift_overlay.o` when putting
together the static library `libdispatch.a`.
This patch fixes this problem is a pretty crude way. The real problem is that
libtool doesn't understand Swift. So it can't be used when compiling
`swift_overlay.o`. In order to still get a …
> fix libdispatch.a to include Swift overlay symbols

- dispatch/dispatch.h
Fixes CI CF build failure (presumably because it has its own fallback definition of API_AVAILABLE but not API_DEPRECATED_WITH_REPLACEMENT)
> provide fallback definitions for all API_* macros

- dispatch/dispatch.h
> Swift 3.1: provide fallback definitions for all API_* macros

- tests/Makefile.am
this test started failing in the CI after the merge of #215
https://ci.swift.org/job/swift-PR-Linux-smoke-test/5128/
> Temporarily move dispatch_context_for_key test into the unreliable tests

- INSTALL.md
- src/shims/lock.h
add dependency on linux-libc-dev to INSTALL.md for other architectures
> remove unused dependency on linux/membarrier.h for intel to fix CI build

- INSTALL.md
- src/shims/lock.h
add dependency on linux-libc-dev to INSTALL.md for other architectures
backport of #221 for swift 3.1
> Swift 3.1: remove unused dependency on linux/membarrier.h for intel to fix CI build

- src/BlocksRuntime/data.c
- src/BlocksRuntime/runtime.c
- src/source.c
- tests/dispatch_data.c
Collection of small fixes to eliminate compiler
warnings when building libdispatch and its tests.
> fixes for compiler warnings

- tests/dispatch_test.c
Implement dispatch_test_check_evfilt_read_for_fd test method
for the event_epoll backend.
> SR-4026: dispatch_test_check_evfilt_read_for_fd for epoll

- src/swift/Dispatch.apinotes
- src/swift/DispatchStubs.cc
- src/swift/Source.swift
- src/swift/Wrapper.swift
(Radar rdar://problem/30518517)
> Adding DISPATCH_SOURCE_TYPE_DATA_REPLACE to the Swift overlay

- src/swift/Data.swift
> Add support for UnsafeRawBufferPointer to DispatchData

- src/shims/lock.h
s390x has a strong memory model and does not require membarrier.
This is the same as https://github.com/apple/swift-corelibs-libdispatch/pull/234 but for the 3.1 branch
> Fix compile error on s390x in shims/lock.h

- dispatch/darwin/module.modulemap
- dispatch/generic/module.modulemap
- private/darwin/module.modulemap
- private/generic/module.modulemap
libdispatch has an umbrella header, dispatch.h, that should be used for
including all of the other headers.  This is enforced via
__DISPATCH_INDIRECT__.
Since it isn't legal to include one of the other headers on their own,
it isn't logical to have submodules for them.  Moreover, submodules
*should* have local visibility (be unaware of the context they're
included from); meaning that __DISPATCH_INDIRECT__ will never be
defined.
Logically, all of the headers are part of a single module/interface.
Patch by me & Duncan P. Exon Smith
> libdispatch: Avoid submodules for headers that should not be included

- src/swift/Time.swift
> Port changes to Time.swift from the swift repository.

- CMakeLists.txt
- cmake/config.h.in
- cmake/modules/DispatchAppleOptions.cmake
- cmake/modules/FindLibRT.cmake
- dispatch/CMakeLists.txt
- man/CMakeLists.txt
- os/CMakeLists.txt
- private/CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
This is far from complete, but is sufficient to build a Linux version of
libdispatch.  It shows what a potential cmake based build system could
look like, and if desired can be completed to build all the various
flavours with cmake.
> build: add a cmake based build system

- src/shims/lock.h
Fixes the build on powerpc64le under Linux.
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
> internal: Move shims include so DISPATCH_INTERNAL_CRASH is defined

- src/shims/lock.h
This fixes the issues described in #233 for Swift 3.1.x
> [Cherry Pick] lock: Avoid use of undefined DISPATCH_INTERNAL_CRASH

- cmake/modules/SwiftSupport.cmake
- src/CMakeLists.txt
Introduce support for building the swift SDK overlay into the CMake
based build system.  This was the one piece which was missing from the
original cmake port of the build system.
> build: attempt to add swift support to cmake

- src/event/event_epoll.c
- src/init.c
- src/internal.h
- src/queue.c
The observed bug is that signals sent to the main thread
after it called dispatch_main were not triggering the
event handler of a DispatchSourceSignal that had been
previously created and activated to handle that signal.
If plausible signals are added to the sigsuspend mask,
then they are properly routed to the signalfd and the
DispatchSourceSignal event handler runs as expected.
This commit also changes event_epoll to use pthread_sigmask
to block the signal when creating a signalfd because
the Linux man page for sigprocmask states that sigprocmask's
behavior is undefined for multi-threaded programs and
pthread_sigmask should be used instead.
> SR-4201: DispatchSourceSignal not working on Linux

- src/event/event_kevent.c
- src/object_internal.h
- src/queue_internal.h
- src/shims/hw_config.h
- tests/dispatch_queue_finalizer.c
This introduces a new macro, `DISPATCH_PTR_SIZE` which is defined much
like `LLVM_PTR_SIZE`.  We can gracefully fallback to alternate means of
checking the width of the pointer and use this rather than `__LP64__` to
determine if we are on a 64-bit host.
> Create a DISPATCH_PTR_SIZE macro and use it

- CMakeLists.txt
- dispatch/dispatch.h
- os/object.h
- os/object_private.h
- src/CMakeLists.txt
Add some cl flags handling to the build system.  Improve macros for Windows builds to detect the target correctly.  This is not enough to perform a full Windows build yet but addresses some of the low hanging fruit.
> Windows cleanups

- cmake/modules/SwiftSupport.cmake
This fixes a typo in the build system which is important because it
fixes the dependency tracking and the output location for the swift doc
that is generated for the swift SDK overlay.
> build: fix typo in build system

- src/allocator.c
- src/allocator_internal.h
Reverts apple/swift-corelibs-libdispatch#242
breaks the build on Darwin with
```
In file included from libdispatch/src/allocator.c:22:
libdispatch/src/allocator_internal.h:240:5: error: function-like macro 'sizeof' is not defined
#if SUPERMAPS_TO_MAPS_PADDING > 0
^
libdispatch/src/allocator_internal.h:168:3: note: expanded from macro 'SUPERMAPS_TO_MAPS_PADDING'
SIZEOF_SUPERMAPS + HEADER_TO_SUPERMAPS_PADDING + SIZEOF_HEADER))
^
libdispatch/src/allocator_internal.h:159:27: note: expanded from macro 'SIZEOF_SUPERMAPS'
#define SIZEOF_SUPERMAPS (BYTES_PER_SUPERMAP * SUPERMAPS_PER_MAGAZINE)
^
libdispatch/src/allocator_internal.h:125:28: note: expanded from macro 'BYTES_PER_SUPERMAP'
#define BYTES_PER_SUPERMAP sizeof(bitmap_t)
^
libdispatch/src/allocator_internal.h:248:5: error: function-like …
```
> Revert "Use sizeof more pervasively"

- src/swift/Queue.swift
Otherwise you can never clear anything you set
> [Overlay/Queue]: Allow setting an optional  value in setSpecific

- private/queue_private.h
- src/queue.c
- src/swift/Queue.swift
This is a resubmission of a callback hook required when mixing multi threaded Swift and Java on Android. When Java JNI has been used on a thread the thread needs to be detached from JNI before the thread exits to free local variables or the application will crash e.g. https://github.com/SwiftJava/java_swift/blob/master/Sources/JavaJNI.swift#L25.
Introducing this hook gives any future Java integration code a chance to do this.
> Thread detach hook for Java JNI on Android

- CMakeLists.txt
- cmake/config.h.in
- src/CMakeLists.txt
This updates the CMake build to bring it to parity with the autotools build.  It also cleans up some of the custom list management for more modern approaches.
> cmake parity updates

- CMakeLists.txt
Use a darwin specific modulemap on darwin, and the generic one
elsewhere.
> build: switch the module map according to the target

- CMakeLists.txt
- src/CMakeLists.txt
This used to be an option in the autotools build.  Address the TODO item
and add an option to control that.
> build: add option to use the gold linker

- cmake/modules/DTrace.cmake
- src/CMakeLists.txt
Add the missing support for dtrace header script support.
> build: add dtrace USDT probe support

- tests/dispatch_queue_finalizer.c
The DISPATCH_SIZEOF_PTR caused a test to go down the wrong path.  This
fixes the test and accounts for the Windows 64 bit case as well (which
is not a LP64 environment).
> tests: fix test build

- src/CMakeLists.txt
- tests/CMakeLists.txt
Remove the supporting code for WITH_PTHREAD_WORKQUEUES which was removed
previously.  NFC.
> build: remove dead code

- src/swift/DispatchStubs.cc
- This allows it to be used by Foundation so that the duplicate
function can be removed from CFRuntime.c in corelibs-foundation.
- This also makes the export match the symbol in libdispatch.a.
Since SwiftFoundation depends on libdispatch, there is no reason to have the function defined in both libraries. It shouldnt break the build as Foundation uses the linker argument `--allow-multiple-definition` but once this PR has been merged the duplicate function can be removed from Foundation and the linker argument eliminated.
At some point in the future the swift compiler may be fixed to not require this work around and then it can be removed from libdispatch as well.
> Export objc_retainAutoreleasedReturnValue()

- src/CMakeLists.txt
All of the swift projects that depend on finding libdispatch.so
during their builds (swift, foundation, swiftpm) all expect it
to be in src/.libs/libdispatch.so (libtool convention). Temporarily
add a rule to copy the built library to where libtool would have
placed it to decouple using CMake for libdispatch from updating
all of the other dependent projects' build expectations.
> CMake compatibility with Swift build assumptions

- CMakeLists.txt
There may be a more elegant way to do this, but we really want
to build shared libraries by default on Linux and we want to
build the test cases and be able to run them.
> Set CMake defaults to match autoconf Linux behavior.

- tests/CMakeLists.txt
Add hook to enable passing in the location of the swift
runtime libraries so we can include them when building
test executables.  If we don't do this and we built
dispatch as a shared library and enabled swift support
the link step fails.
> link swift libraries when building test executables

- tests/CMakeLists.txt
Create an imported library target for the runtime libraries rather than
add the explicit library search path handling.  This avoids the need for
the rpath in the tests, and allows cmake to properly model dependencies.
It also makes the build system more amenable to
cross-compiling/cross-linking by avoiding ELF linker specific options.
> build: avoid rpath, library search path handling

- tests/bsdtestharness.c
- tests/bsdtests.c
- tests/bsdtests.h
- tests/dispatch_after.c
- tests/dispatch_api.c
- tests/dispatch_apply.c
- tests/dispatch_c99.c
- tests/dispatch_data.c
- tests/dispatch_group.c
- tests/dispatch_io_net.c
- tests/dispatch_queue_finalizer.c
- tests/dispatch_select.c
- tests/dispatch_sema.c
- tests/dispatch_starfish.c
- tests/dispatch_timer.c
- tests/dispatch_timer_bit31.c
- tests/dispatch_timer_bit63.c
- tests/dispatch_timer_set_time.c
- tests/dispatch_timer_short.c
- tests/linux_port.h
fixes to allow clean compilation of test suite with addtional
clang warnings enabled.
> test suite fixes to prep for enabling additional warnings

- tests/bsdtestharness.c
- tests/bsdtests.c
- tests/bsdtests.h
- tests/dispatch_after.c
- tests/dispatch_api.c
- tests/dispatch_apply.c
- tests/dispatch_c99.c
- tests/dispatch_data.c
- tests/dispatch_group.c
- tests/dispatch_io_net.c
- tests/dispatch_queue_finalizer.c
- tests/dispatch_select.c
- tests/dispatch_sema.c
- tests/dispatch_starfish.c
- tests/dispatch_timer.c
- tests/dispatch_timer_bit31.c
- tests/dispatch_timer_bit63.c
- tests/dispatch_timer_set_time.c
- tests/dispatch_timer_short.c
- tests/linux_port.h
Reverts apple/swift-corelibs-libdispatch#274
I believe this broke the build, eg https://ci.swift.org//job/oss-swift-incremental-RA-linux-ubuntu-14_04/3550/consoleFull#1160775376ee1a197b-acac-4b17-83cf-a53b95139a76
```
/home/buildnode/disk2/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04/swift-corelibs-libdispatch/tests/bsdtests.h:72:72: error: expected function body after function declarator
void test_ptr_notnull_format(const void *ptr, const char *format, ...) __printflike(2, 3);
^
/home/buildnode/disk2/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04/swift-corelibs-libdispatch/tests/bsdtests.h:80:89: error: expected function body after function declarator
void test_ptr_format(const void* actual, const void* expected, const char *format, ...) __printflike(3,4);
^
```
> Revert "test suite fixes to prep for enabling additional warnings"

- dispatch/once.h
- src/once.c
- src/shims/lock.h
By not inlining the fastpath of dispatch_once() when the hardware cannot
give us the right semantics.
> Remove dependency on sys_membarrier on linux

- src/event/event_epoll.c
_dispatch_epoll_update() was being called without dmn->dmn_events being
updated beforehand.
Signed-off-by: Pierre Habouzit <phabouzit@apple.com>
> Actually update epoll events if needed when unregistering

- src/event/event_epoll.c
- tests/dispatch_timer.c
Make sure we don't keep doing these syscalls and log stupid errors about
it failing forever.
> the buffer size ioctls on linux return EINVAL when it's not supported

- src/event/event_epoll.c
(the issue was reported to me privately)
> Fix improper double-fire of signal sources on Linux

- src/BlocksRuntime/runtime.c
- src/data.c
- src/event/event_epoll.c
- src/event/workqueue.c
- src/internal.h
- src/io.c
- src/queue.c
- src/shims/hw_config.h
- src/shims/lock.c
- src/shims/lock.h
- src/swift/DispatchStubs.cc
- src/voucher.c
work in progress on cleaning up code so it can be compiled
with the same set of warning flags used on Darwin. This is an inital
pass through the C files in src to resolve warnings. Most warnings
are related to implicit size/sign conversions between integral types.
> fixes to src to prep for enabling additional compiler warnings

- tests/CMakeLists.txt
Port over test-specific compilation flags and support for
lenient deadlines for running in the Swift CI from Makefile.am
> CMake: carry over some nuances from autotools test config

- tests/dispatch_group.c
Ensure that we do not attempt a divide-by-zero.  Adjust the loop count
accordingly.
> tests: fix undefined behaviour

- tests/bsdtestharness.c
Ensure that the variable is referenced to avoid an unused variable
warning from GCC/clang when building the tests in a Release+NoAsserts
configuration.  This is done as part of the swift build on Linux for
SourceKit.
> test: avoid -Wunused-variable on NoAsserts build

- CMakeLists.txt
- cmake/modules/DispatchSanitization.cmake
Add support to configure the build to use sanitizers to aid in finding
issues.  The `DISPATCH_USE_SANIZITERS` is a cmake option that defaults
to none, but can be one of `Address`, `Memory`, `MemoryWithOrigins`,
`Undefined`, `Leaks`, `Address;Undefined`.  This allows for easily building
libdispatch and the tests with the sanitizers.
> build: add support to build with sanitization

- CMakeLists.txt
- cmake/config.h.in
- os/linux_base.h
Newer versions of glibc indicate that they intend to move the `major`
macro from `sys/types.h` to `sys/sysmacros.h`.  Add a check for the
header and include that earlier to ensure that the macro is provided by
the newer header when available/possible.  This avoids an unnecessary
warning from the system headers.
> linux: update header used for `major` macro

- tests/bsdtests.c
- tests/bsdtests.h
- tests/dispatch_cascade.c
- tests/dispatch_concur.c
- tests/dispatch_drift.c
- tests/dispatch_io.c
- tests/dispatch_pingpong.c
- tests/dispatch_priority.c
- tests/dispatch_read.c
- tests/dispatch_read2.c
- tests/dispatch_readsync.c
- tests/dispatch_suspend_timer.c
Fixes to build the extended test suite
(not built/run under Swift CI) when using
the expanded set of compiler warning flags.
> Fix compilation warnings in extended test suite

- tests/bsdtests.c
- tests/bsdtests.h
- tests/dispatch_cascade.c
- tests/dispatch_concur.c
- tests/dispatch_drift.c
- tests/dispatch_io.c
- tests/dispatch_pingpong.c
- tests/dispatch_priority.c
- tests/dispatch_read.c
- tests/dispatch_read2.c
- tests/dispatch_readsync.c
- tests/dispatch_suspend_timer.c
Reverts apple/swift-corelibs-libdispatch#290
Sorry to revert, but this breaks Swift CI incremental bots and PR testing (so it's blocking all other work)
swift-corelibs-libdispatch/os/linux_base.h:16:10: fatal error: 'config/config_ac.h' file not found
#include <config/config_ac.h>
^
https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04/4182/console
> Revert "Fix compilation warnings in extended test suite"

- CMakeLists.txt
- cmake/config.h.in
- os/linux_base.h
Reverts apple/swift-corelibs-libdispatch#286
Sorry to revert, but this breaks Swift CI incremental bots and PR testing (so it's blocking all other work)
swift-corelibs-libdispatch/os/linux_base.h:16:10: fatal error: 'config/config_ac.h' file not found
#include <config/config_ac.h>
^
https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04/4182/console
> Revert "linux: update header used for `major` macro"

- tests/bsdtests.c
- tests/bsdtests.h
- tests/dispatch_cascade.c
- tests/dispatch_concur.c
- tests/dispatch_drift.c
- tests/dispatch_io.c
- tests/dispatch_pingpong.c
- tests/dispatch_priority.c
- tests/dispatch_read.c
- tests/dispatch_read2.c
- tests/dispatch_readsync.c
- tests/dispatch_suspend_timer.c
This restores pull request #290 from dgrove-oss/fix-warnings-extended-tests.
This was an accidental revert. Somehow the revert button on github led
me to the wrong PR.
> Reapply "Fix compilation warnings in extended test suite".

- src/event/event_epoll.c
This fixes issues around resuming or re-registering file-descriptors with
a previously triggered EPOLLONESHOT event.
Signed-off-by: Pierre Habouzit <phabouzit@apple.com>
Fixes: SR-5759
> Track armed events in muxnotes closely

- src/event/event_epoll.c
It is possible for _dispatch_muxnote_create to return NULL, this error
condition was not being handled in dispatch_unote_register leading to
an immediate SIGSEGV when it happened.
> SR-4677: avoid SIGSEGV if _dispatch_muxnote_create returns NULL

- CMakeLists.txt
- src/CMakeLists.txt
This adjusts the symlink creation so that it always occurs.  This also
allows us to ensure that we wire up the dependency for the swift module
to the symlink creation.  The CMake based build would fail without this
when trying to build dispatch for SourceKit on Linux.
> build: fix symlink creation

- src/swift/Time.swift
This is the swift-corelibs-libdispatch version of the PR at https://github.com/apple/swift/pull/11927.
Fixes overflows in DispatchTime/DispatchWallTime/DispatchTimeInterval.
Examples:
DispatchTime.now() + Date.distantFuture.timeIntervalSinceNow // traps
DispatchTime.now() + Date.distantPast.timeIntervalSinceNow. // traps
let t = DispatchTimeInterval.seconds(Int.max)
t == t // Traps due to conversion to nanoseconds.
rdar://problem/34440944
> Fix overflow traps in DispatchTime/DispatchWallTime/DispatchTimeInterval

- src/event/event_epoll.c
Changes for SR-5759 introduced a bug where disarmed events got dropped when
a muxnote is reused, due to erroneously setting dmn->dmn_events to the
combination of new events and currently armed events.
Combining existing events with the combination of new events and armed events
implements the intended behavior.
> Properly pick up new events when reusing a muxnote

- INSTALL.md
Update the documentation to reference the CMake build infrastructure
rather than autotools for the non-Darwin targets.  Once the Darwin build
is switched over, the entire build process can be described in a single
block.
> docs: update documentation to show how to use CMake

- src/transform.c
Most targets use unsigned chars.  Explicitly change the static tables to
`signed char`.  An alternative  would be to force signed chars during
the compilation of libdispatch.  When building for Linux AArch64, the
use of `-1` causes signed conversion warnings when initializing the
table.
> Attempt to be better with signed conversions

- CMakeLists.txt
- dispatch/CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
Add explicit links against the swift runtime for the tests which may
use the swift runtime.  This prevents link failures for the swift tests.
> build: explicitly link tests to swiftCore swiftOnoneSupport

- cmake/modules/SwiftSupport.cmake
Add a dependency on the swift compiler to ensure that a change to the
compiler will rebuild the swift portions.
> build: add a dependency on the swift compiler

- private/queue_private.h
This is literally a one-liner that is not even a code change, but it fixes a warning that gets promoted to an error in the Android build
> Fix documentation warning in queue_private.h

- src/CMakeLists.txt
Adjust install path for libdispatch in CMakelists.txt
> SR-6084: libdispatch.so missing from snapshot builds

- dispatch/CMakeLists.txt
- os/CMakeLists.txt
- src/CMakeLists.txt
https://bugs.swift.org/browse/SR-6084
<rdar://problem/35040697> [SR-6084]: libdispatch missing from Trunk Development snapshots
> Fix the install path for the toolchain

- CMakeLists.txt
Looks like overriding this from CLI did not work so hardcode it for now.
> [CMake] Set CMAKE_INSTALL_LIBDIR path

- CMakeLists.txt
- dispatch/CMakeLists.txt
- os/CMakeLists.txt
- src/CMakeLists.txt
CMAKE_INSTALL_LIBDIR has wrong value during a clean build for some
reason.
> [CMake] Use a custom variable for libdir path

- src/event/event_epoll.c
- src/source.c
- tests/dispatch_starfish.c
- tests/dispatch_timer.c
I ran into some compilation failures while building on the Raspberry PI Model 3. These issues were simply type conversion warnings that resulted in errors (due to -Werror in the compilation settings.)
There may be more related issues, but what is attached is the minimal set of changes required to get it to build for me.
My setup: Raspberry PI 3 Model B
```
$ uname -a
Linux rpi 4.9.37-v7+ #1017 SMP Thu Jul 13 11:26:04 BST 2017 armv7l armv7l armv7l GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
${SRCROOT}/swift/utils/build-script --preset=buildbot_linux_1604 install_destdir="${SRCROOT}/__install"  installable_package="${SRCROOT}/__install.tar.gz"
```
My apologies for not …
> A few updates to enable building on Raspberry PI/Ubuntu 16.04

- configure.ac
- src/shims/time.h
Caught this today; _dispatch_approximate_time() uses CLOCK_REALTIME on Linux for some reason, while _dispatch_absolute_time() uses CLOCK_MONOTONIC. This seems wrong and I can't think of a reason why this would be desirable in the first place.
Darwin code uses the same clock family for both, so use CLOCK_MONOTONIC_COARSE on Linux as the approximate time source, and test for it during configure.
> Base approximate time on a monotonic clock, like absolute time

- CMakeLists.txt
- cmake/modules/SwiftSupport.cmake
- src/CMakeLists.txt
Use `add_custom_command` and `add_custom_target`.  This ensures that the
ordering dependencies are properly honoured by ninja.  This fixes an
issue where sometimes I would see `swiftDispatch` being built prior to
the module map symlinks being established.
> build: ensure that dependencies are tracked properly

- src/event/event_epoll.c
On Linux systems, ev.data is an 8-byte field, but this code currently initializes only 4 bytes of the field, leaving the trailing 4 bytes unininitialized. This causes memory safety tools like Valgrind to complain, as noted in #321.
This patch no longer explicitly initializes `.data`, ensuring that C structure initialization will force the `.data` field to be zero-initialized. Manual checks of the compiled binary show that the compiler correctly initializes the 4 bytes for `.u32` only once, so this change incurs minimal overhead (specifically, setting the next 4 bytes to 0).
> Fully initialize ev.data.

- CMakeLists.txt
- cmake/modules/SwiftSupport.cmake
This PR improves host detection to provide the same logic being used in [Swift](https://github.com/apple/swift/blob/master/CMakeLists.txt#L541).
Instead of using the specific `${CMAKE_SYSTEM_PROCESSOR}` directly, this value should be used to choose a more generic variant.
No changes needed for ${SWIFT_OS}.
This PR also fixes an issue on ARM, where at the moment `SWIFT_RUNTIME_LIBDIR` points to `.../armv7l/` instead of `.../armv7/`.
/cc @compnerd
> Improve host architecture detection

- CMakeLists.txt
- dispatch/CMakeLists.txt
- os/CMakeLists.txt
- private/CMakeLists.txt
- src/CMakeLists.txt
- src/internal.h
- src/shims.c
- src/shims.h
- src/shims/linux_stubs.h
- tests/CMakeLists.txt
- tests/bsdtests.h
- tests/dispatch_group.c
- tests/dispatch_queue_finalizer.c
This patch allows building libdispatch with a wider range of dependencies on Linux systems. This also removes references to ‘swift’ in paths if Swift is not enabled.
> Allow building on wider range of dependencies on Linux

- tests/CMakeLists.txt
Seek to avoid spurious test timeouts in Swift CI by
raising limit for individual test execution from 30
seconds to 120 seconds.
> Increase test timeout value by 4x

- os/object_private.h
- src/apply.c
- src/block.cpp
- src/event/event.c
- src/event/event_config.h
- src/event/event_kevent.c
- src/firehose/firehose_buffer.c
- src/firehose/firehose_inline_internal.h
- src/init.c
- src/inline_internal.h
- src/internal.h
- src/introspection.c
- src/io.c
- src/object_internal.h
- src/queue.c
- src/shims.h
- src/shims/atomic.h
- src/shims/atomic_sfb.h
- src/shims/lock.c
- src/shims/yield.h
- src/source.c
- tests/Foundation/bench.mm
- tests/dispatch_transform.c
Use the reserved spelling for `asm` as it is a non-standard compiler
extension.  NFC.
> use reserved spelling for inline assembly

- src/BlocksRuntime/runtime.c
This adjust the BlocksRuntime to work on Windows x64 which is an LLP64
environment.  This primarily comes down to using `size_t` for the size
parameter for the allocation routines.  A secondary change which is
needed is the type cast for the `InterlockedCompareExchange` operation
on Windows.  A small cleanup is included which removes the definition of
an unused function.
> BlocksRuntime: adjust implementation for Windows x64

- src/swift/Block.swift
- src/swift/Dispatch.swift
- src/swift/Queue.swift
- src/swift/Source.swift
Ref: https://github.com/apple/swift/pull/15230
> [gardening] Prefer macOS over OSX for `available`

- src/swift/IO.swift
- src/swift/Queue.swift
Ref: https://github.com/apple/swift/pull/15142
---
The initializers used here are not optional ones, so there is no need to use `flatMap`.
- https://github.com/apple/swift-corelibs-libdispatch/blob/9295346d20e52c9ff4d82906fd85287d8636c542/src/swift/Data.swift#L100-L102
- https://github.com/apple/swift-corelibs-libdispatch/blob/9295346d20e52c9ff4d82906fd85287d8636c542/src/swift/Queue.swift#L22-L25
> [gardening] Use `Optional.map` over `flatMap` where appropriate

- CMakeLists.txt
- src/CMakeLists.txt
For cross-compiling to Windows, lld is a requirement.  It also can be
used for ELF targets.  Add an option to have lld be used as the linker
to mirror the gold option.
> build: support lld as the linker

- CMakeLists.txt
- src/CMakeLists.txt
When building for Windows on Linux, we need to explicitly setup the
linker search paths.  These are derivable from the UCRT version and the
WinSDK base directories which are expected environment variables.  This
is also how the swift build system finds the directories.  Enable this
to avoid having the user explicitly setup the `LIB` environment variable
for the linker to find the system import libraries.
> build: add the default search paths for Windows

- src/swift/Data.swift
The deprecation warning guides us towards UnsafeRawBufferPointer, so sure, let's use that.
Corelibs version of apple/swift#16080. No intended functionality change.
> Simplify DispatchData.append(_: UnsafeBufferPointer<T>)

- CMakeLists.txt
- cmake/config.h.in
- src/init.c
- src/shims/tsd.h
When building for Windows, shims/tsd.h declares __dispatch_tsd with
__declspec(thread). init.c needs to match this or else it will not compile with
newer versions of Clang.
> Use _Thread_local for thread-local storage

- CMakeLists.txt
- cmake/modules/DispatchUtilities.cmake
- src/CMakeLists.txt
- tests/CMakeLists.txt
This ensures that the cmake used to build is the cmake invoked when
running the custom command.  In the case that `cmake` is not in PATH,
you would fail to invoke the command, failing the build.
> build: use `CMAKE_COMMAND` instead of hardcoded cmake

- cmake/modules/ClangClCompileRules.cmake
ClangClCompileRules.cmake overrides CMAKE_C_LINK_EXECUTABLE to invoke the C
compiler, but clang-cl does not accept linker flags, so tests will fail to link.
The default is fine, so delete this line.
> build: fix the clang-cl executable link command

- src/CMakeLists.txt
This PR fixes the install path for Dispatch.swiftmodule/Dispatch.swiftdoc and a few other headers on the armv6/v7 platforms.
It's an extension to PR #322, and again, replaces `${CMAKE_SYSTEM_PROCESSOR}` with the new `${SWIFT_HOST_ARCH}`.
> Fix install path

- cmake/modules/DispatchWindowsSupport.cmake
Invoking cmake on a system where MSVC (2017) sets the PROCESSOR_ARCHITECTURE environment variable to AMD64 would previously fail with this error:
`CMake Error at cmake/modules/DispatchWindowsSupport.cmake:12 (message):
do not know MSVC spelling for ARCH: `AMD64`
Call Stack (most recent call first):
CMakeLists.txt:331 (dispatch_windows_arch_spelling)`
We now treat AMD64 like x86_64.
> Fixed handling of the AMD64 processor architecture on Windows

- tests/CMakeLists.txt
clang-cl does not support -fblocks, so prefix it with -Xclang to pass it
directly to the frontend like src/CMakeLists.txt does.
> build: correctly enable blocks for tests when using clang-cl

- CMakeLists.txt
- INSTALL.md
- cmake/modules/FindBlocksRuntime.cmake
- src/CMakeLists.txt
- tests/CMakeLists.txt
This uses the standard CMake mechanism for finding the blocks runtime.
If one is not found, one will be provided for you.
> build: support system installed BlocksRuntime

- src/CMakeLists.txt
- src/internal.h
- src/shims.h
- src/shims/generic_sys_queue.h
Added a copy of the Apple / Darwin sys/queue.h and hooked things up such that we use that one when building on Windows because the Windows SDK doesn't come with a sys/queue.h header.
> added a sys/queue.h implementation for Windows

- src/internal.h
Provide a Windows implementation of the `_dispatch_set_crash_log_*` macros which
pass the crash message to the CRT using _RPTF0. If libdispatch is linked against
a debug version of msvcrt, this will display a dialog with detailed information
about the crash and provide an option to attach a debugger. On release versions
of msvcrt, this reporting is a no-op.
Example of what this dialog looks like (from an actual issue I encountered):
> Report crash messages on Windows to the CRT

- src/CMakeLists.txt
- src/shims/getprogname.c
- src/shims/getprogname.h
We use GetModuleFileName() to get the filename of the process.  InitOnceExecuteOnce() is used to do this once per app run.
> implemented getprogname() for Windows

- src/BlocksRuntime/Block_private.h
The Blocks ABI v1 defined the `size` and `reserved` fields as `unsigned
long int` rather than `uintptr_t`.  This breaks on LLP64 hosts where
`uintptr_t` is larger than `unsigned long int`.  Make this conform to
the specification.
> BlocksRuntime: match the ABI specification for LLP64

- dispatch/base.h
Added MSVC specific definitions of the DISPATCH_* macros to dispatch/base.h. This is one necessary step to make it possible to compile the Swift APIs for ibdispatch. E.g. we need a working definition of DISPATCH_NORETURN to ensure that we can successfully compile his function:
`public func dispatchMain() -> Never {
CDispatch.dispatch_main()
}`
because its return type is `Never`.
DISPATCH_* macros which are empty are empty because MSVC has no equivalent to the corresponding clang / gcc attribute.
> Added MSVC definitions for the DISPATCH_* macros in dispatch/base.h

- src/internal.h
- src/shims/generic_win_stubs.h
_snprintf does not guarantee null termination if the size argument is too small.
Starting with VS2015, the UCRT provides a C99-compliant snprintf. Use it, and
also fix a related issue where _dispatch_client_assert_fail was passing a
too-small size.
> Use snprintf instead of _snprintf on Windows

- tests/CMakeLists.txt
Same fix that we did for CMakeLists.txt but this time for the cmake file in tests.
> Windows doesn't support symlinks so use copy instead (tests/CMakeLists.txt)

- src/CMakeLists.txt
- src/event/event_config.h
- src/event/event_internal.h
- src/event/event_windows.c
- src/shims/generic_win_stubs.c
- src/shims/generic_win_stubs.h
Provide stubs for unimplemented Windows functions so that dispatch.dll can link
and we can start building the tests. If one of these stubs is called, it will be
reported to the CRT.
> Stub out unimplemented Windows functions

- src/queue.c
There's a quirk on Windows where exiting the process will still run fiber-local
storage destructors for the thread that called ExitProcess() (but only for that
thread). pthreads-based platforms don't call any key destructors on exit, and
_libdispatch_tsd_cleanup() assumes this. So, on Windows, calling exit() from a
queue thread will trigger the fatal error in _dispatch_frame_cleanup().
Implement a reliable method of detecting whether the process is exiting, and if
it is, ignore calls to _libdispatch_tsd_cleanup().
> Ignore Windows FLS destructors during process exit

- src/swift/Queue.swift
rdar://problem/40951342
Adds documentation comments to dispatch queue-related methods.
> Add documentation comments.

- src/CMakeLists.txt
CMakeLists.txt checks for librt's presence but the result is never used. This
causes a link failure on systems where clock_gettime() is provided by librt.
> build: link against librt if it's available

- src/CMakeLists.txt
When building debug, swift requires a supplementary library.  The swift driver
is aware of this and will make the appropriate arrangements.  However, since the
swift component is compacted into the C library, the linker driver being used
does not understand this requirement.  Explicitly link against the support
library.  This allows building the debug configuration of libdispatch with a
release configuration of the swift standard library.
> build: link against swiftOnoneSupport in debug configuration

- CMakeLists.txt
- cmake/modules/DispatchWindowsSupport.cmake
- src/CMakeLists.txt
- tests/CMakeLists.txt
Allow libdispatch to be embedded in other CMake projects using
add_subdirectory(). This essentially means that `CMAKE_SOURCE_DIR` and
`CMAKE_BINARY_DIR` cannot be used directly. Use the versions of these variables
which are scoped to the current project or directory.
> build: support embedding in other CMake projects

- src/swift/Time.swift
This hack was only needed for Swift 3 mode in a narrow case.  Now that
we're dropping Swift 3 from master, the source break this was working
around is no longer relevant.
> Drop @_downgrade_exhaustivity_check attribute

- src/swift/Queue.swift
This patch aims to make swift-corelibs-libdispatch adapted to [this PR](https://github.com/apple/swift/pull/18895), which warns for version number in 'available' attribute for non-specific platform '*'.
> Remove version number used in 'available' attribute for non-specific platform '*'.

- src/swift/Dispatch.swift
- src/swift/IO.swift
- src/swift/Queue.swift
- src/swift/Source.swift
This patch aims to make corelibs-libdispatch adapted to [this PR](https://github.com/apple/swift/pull/18623), which produces warnings for redundant access-level modifiers.
Following [INSTALL.md](https://github.com/apple/swift-corelibs-libdispatch/blob/master/INSTALL.md), I have troubles building libdispatch. It seems the instructions are not up-to-date. It suggests building with `autoconf` while instead `cmake` should be used at the moment...
@mwwa Hi Matt, would you help review this, please?
> Fix redundant access-level modifiers.

- CMakeLists.txt
- dispatch/generic/module.modulemap
This is needed for proper shared linkage to the BlocksRuntime (e.g. when
building SourceKit).  We now build BlocksRuntime shared or static as requested.
> build: honour `BUILD_SHARED_LIBS`

- src/CMakeLists.txt
Because we are linking libdispatch through clang rather than swift, we need to
explicitly add swiftrt.o, which is needed by ELF and COFF to register metadata
sections. Fixes rdar://problem/44941707.
> [CMake] Make sure to link swiftrt.o when building the Swift Dispatch overlay.

- src/swift/Block.swift
This fixes an error from the swift compiler:
error: cannot convert value of type 'UInt32' to expected argument type 'UInt'
> swift: cast to the appropriate type

- src/queue.c
clang objects to the `default` case in a covered switch:
src/queue.c:1127:2: error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default]
Remove the label, relying on the covered switch to catch the issue.
> queue: clean up a covered switch

- private/queue_private.h
- src/queue.c
This function is declared as accepting a `dispatch_function_t` callback, which
is a function pointer with a `void *` argument. However, the implementation and
Swift overlay declare the callback without arguments, causing a conflict which
Clang warns about. Change the function signature to accept the correct type.
> Fix the signature of _dispatch_install_thread_detach_callback()

- CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
Adjust the paths for static runtime builds of Swift.
> build: support static builds for Swift

- tests/dispatch_c99.c
Some C libraries (e.g. Bionic on Android) provide a `__printflike()` macro but
this test always redefines it on Linux-based systems. bsdtests.h already has
better logic to ensure it is available.
> dispatch_c99: remove unnecessary __printflike() definition

- CMakeLists.txt
Change from a symlink to a copy.  This is more portable and fixes the
distribution aspect.  When the installation occurs, the symbolic link is
not followed and a symbolic link is installed.  Rather if we copy, we
can get the contents.  The files are small so the cost is relatively
low.
> build: always copy the modulemaps

- cmake/modules/SwiftSupport.cmake
- src/CMakeLists.txt
- tests/CMakeLists.txt
This splits out the SDK overlay component and libdispatch runtime itself. Doing
so enables the re-use of libdispatch with and without swift and makes the
behaviour similar across Darwin and other platforms.
The goal here is to actually have the same build structure as Darwin on Linux
and Windows. We would have a swiftDispatch library and the core libdispatch
library. The motivation for this is the future work to actually attempt to build
a LSP in swift on the (toolchain) host. We can use the core libdispatch for
SourceKit and then add the swiftDispatch SDK overlay bits for the LSP
components. This avoids having two builds of libdispatch (one with swift support
and one without).
> Split Swift SDK Overlay

- src/CMakeLists.txt
Remove the explicit /usr/include search path for the swift library build.  This
allows us to build for Windows as well.
> build: remove "/usr/include" for swift

- src/swift/Source.swift
- src/swift/Wrapper.swift
Treat windows like Linux and android and remove the BSD interfaces on
these targets.  This allows us to mostly build the SDK overlay for
Windows.
> SDK: guard BSD specific paths against windows

- src/swift/DispatchStubs.cc
Provide an alias for the import symbol as the ObjC runtime is normally
in a separate DLL and the compiler will annotate the function as being
DLLImport.  This allows us to resolve the symbols when building the SDK
overlay.
> DispatchStubs: make more Windows friendly

- dispatch/block.h
- dispatch/group.h
- dispatch/object.h
- dispatch/queue.h
- dispatch/semaphore.h
- dispatch/source.h
- src/event/event.c
- src/event/event_internal.h
- src/queue.c
- src/semaphore.c
- src/semaphore_internal.h
- src/shims/priority.h
- src/source.c
- src/source_internal.h
This attempts to replace the public uses of `unsigned long` with
`uintptr_t` and `long` with `intptr_t`.  The use of `long` and `unsigned
long` here was as a type suitable for matching pointer width.  However,
on LLP64 targets, this does not hold.  Replace them with `intptr_t`
which gives a proper pointer sized type.  This is done only for the
argument types and not for named types to ensure that the ABI is not
modified for C++ (where a template may be specialized on the named
type).
> dispatch: make public interfaces LLP64 friendly

- src/CMakeLists.txt
This removes the compatibility locations that we were populating now
that the consumers should have been updated.
> build: clean up the transition compatibility work

- src/CMakeLists.txt
Ensure that we honour the linker setting when building the swift SDK
overlay.  This is particularly important for android.
> build: honour the USE_*_LINKER flags for swift

- src/CMakeLists.txt
The SDK overlay requires the BlocksRuntime but did not explicitly link
to it.  This works on most platforms, however, Windows requires that all
symbols are fully resolved (effectively `-z defs` on Linux).  Add the
missing dependency.
> build: add an explicit link to BlocksRuntime

- tests/dispatch_io.c
- tests/dispatch_io_net.c
- tests/dispatch_read.c
- tests/dispatch_read2.c
- tests/dispatch_select.c
- tests/dispatch_test.c
- tests/dispatch_test.h
Some tests hardcode `/usr/bin/vi` as a path to a file to read from. This is
definitely not going to exist on Android and Windows. Instead of hardcoding this
path in each test, create a `dispatch_test_get_test_file()` function to retrieve
the path. On Linux and Windows, return the path to the test executable, because
this should be significantly more reliable.
> tests: read from a temporary file instead of vi on non-Apple platforms

- dispatch/dispatch.h
In `Data.swift` the C function `memcpy` is used as part of `_copyBytesHelper`.
The function is declared in `string.h`, but that header is not referenced
directly by any of the headers in `dispatch/` or by `DispatchOverlayShims.h`
in the compiler, which are the only two headers imported by the swift
file.
For some reason, this is working on Darwin and Ubuntu, probably because
some included header includes `string.h` or declares `memcpy`, avoiding the
problem. For those platforms that this already works, adding an extra
include should not affect them.
> Add string.h for memcpy in Data.swift.

- dispatch/dispatch.h
time.h is needed on Windows to ensure that we have a definition of
`timespec`.  This is needed when building the swift SDK overlay.  It
seems that when cross-compiling, we were getting lucky with the
`timespec` definition being provided by some other header being
included.  This repairs the build of libdispatch's swift SDK overlay on
Windows targeting Windows.
> dispatch: include `time.h` on windows

- src/init.c
- src/internal.h
- src/io.c
- src/queue.c
- src/semaphore.c
This cleans up the few warnings that remain when building libdispatch.
It now builds clean of warnings with clang 8.
> libdispatch: clean up some Win64 warnings

- cmake/modules/SwiftSupport.cmake
- src/CMakeLists.txt
This is needed to make the shared+static build for build-script work.  The
primary issue is the dependency on the module-maps doesn't work due to the lack
of add_custom_command, so the target dependency cannot be hooked up.
Additionally, undo the hack for the AST_NAME as we need that to be proper for
the copy to succeed.  Finally, make sure that the we set the location for the
archive output correctly.
> build: make the static build work well

- src/CMakeLists.txt
When building libdispatch as a static library ensure that it is built as
a PIC library.  This is implicit when building a shared library.  If the
library is not built shared, we cannot statically link it on Unix
targets.
This partially resolves SR-9384!
> build: build libdispatch as position independent

- src/swift/Dispatch.swift
`dispatchPrecondition` is great, but it lacks file/line parameters ...
> Pass along source context in `dispatchPrecondition`

- CMakeLists.txt
Now that we link using the swift driver, we no longer need to explicitly
add in the path to the swift registrar.  Remove the unncessary
`find_package` to make it easier to build libdispatch.
> build: remove unnecessary `find_package`

- cmake/modules/DispatchUtilities.cmake
The `-fuse-ld=` parameter requires the executable suffix for this to work on
Windows.  This allows us to cross-compile for android on Windows.
> build: add executable suffix for `-fuse-ld=`

- tests/CMakeLists.txt
- tests/bsdtestharness.c
- tests/bsdtests.c
- tests/bsdtests.h
- tests/dispatch_test.c
- tests/dispatch_test.h
- tests/generic_win_port.c
- tests/generic_win_port.h
This provides a functional Windows port of bsdtestharness and its dependencies
so that we can start running the test suite on Windows. Some tests already build
and run correctly, while others either fail at runtime or don't compile. I'll
be following up with fixes for individual tests later.
> tests: port the test harness to Windows

- src/init.c
- tests/dispatch_debug.c
Port the dispatch_debug test to Windows and fix a bug that it found related to
logfile initialization.
_dispatch_logv_init()'s Windows implementation uses _fdopen() and fprintf() to
write the log header. However, this gives ownership of the file to stdio, so
fclose() closes the descriptor and causes future writes to trigger CRT assertion
failures. Avoid this by using snprintf() and _write() instead.
> dispatch: fix logging to a file on Windows

- src/semaphore.c
Was using PRId64 instead of PRIdPTR, which would be incorrect when compiling for 32-bit.
> Fixed printf format macro for intptr_t arguments.

- private/CMakeLists.txt
These are included by private.h and should be installed alongside.
> Added missing private headers to cmake install.

- src/queue.c
This fixes various "conflicting types for XXX" errors I get when building the project for Android after the recent libdispatch-1121 merge. The changes are not Android-specific though and probably result in warnings or errors on other platforms (depending on -Werror).
> Fixed conflicting method signature for _dispatch_install_thread_detach_callback()

- src/semaphore.c
This is a follow-up patch to #448 after the `dsema_value` field [was changed to `intptr_t`](https://github.com/apple/swift-corelibs-libdispatch/commit/55195b7a16e958c76824f1e6331345278918fc5b#diff-953320a7e70207807bfd163d535dae70) with the latest updates.
> Fix printf format macro for `dsema_value`

- src/shims/yield.h
pthread_yield() is not available on Android.
In combination with #458 this fixes all build issues using Android NDK targeting API level 21 and up.
> Use sched_yield() as fallback for preemption yield

- src/queue.c
with system-provided gettid() in /usr/include/bits/unistd_ext.h that is not static. 
According to https://raw.githubusercontent.com/bminor/glibc/master/ChangeLog, Florian Weimer moved `units_ext.h` from `sysdeps/generic/bits` to `bits` and libdispatch won't compile due to the function having different declarations between the system-provided one and the one defined in `queue.c`. 
I figure that, since it's only being called in one spot in the same file, it was safe to rename the function in without having to make a special #ifdef Linux-only version.
> Added underscores to gettid(void) to remove name clash

- src/internal.h
- src/shims.h
- src/shims/generic_sys_queue.h
TAILQ_CONCAT() and LIST_FOREACH_SAFE() are not defined in [queue.h](https://android.googlesource.com/platform/development/+/73a5a3b/ndk/platforms/android-20/include/sys/queue.h) in the Android NDK.
I simply added the macros to internal.h, but please let me know if you’d prefer another place to add them.
> Added missing queue macros for building on Android

- src/queue.c
The system-provided gettid() was previously used on Android, which broke with the recent symbol change to _gettid() (#461).
Since SYS_gettid is available in recent NDKs (at least since version 21) we can now use that instead and remove the special-casing.
> Use SYS_gettid on Android

- src/init.c
- src/internal.h
> Workaround for Ubuntu 18.04 clang crashes in swift-corelibs-libdispath

- tests/CMakeLists.txt
- tests/dispatch_apply.c
- tests/dispatch_concur.c
- tests/dispatch_io_net.c
- tests/dispatch_priority.c
- tests/dispatch_read.c
- tests/dispatch_read2.c
- tests/dispatch_readsync.c
- tests/dispatch_select.c
- tests/dispatch_test.c
- tests/dispatch_test.h
- tests/generic_win_port.c
- tests/generic_win_port.h
This patch set provides Windows support for most of the remaining test suite. Many of the tests do not pass yet, and I do not expect the test ports themselves to be perfect, but being able to easily build and run everything should be a big step towards fixing all of the remaining issues with the Windows port of Dispatch. In particular, @compnerd and I have been working on implementing socket and file event sources, and we need to be able to easily test everything.
The only test that still needs to be ported is dispatch_io, which may take some time to do since it uses <fts.h>. For now, that test is disabled on Windows just so that it's easy to build everything without ignoring errors. (It won't pass anyway until we have more event sources implemented.)
Most of the complexity here is …
> Port most remaining tests to Windows

- src/event/event.c
- src/event/event_internal.h
File handles and sockets on Windows are pointer sized.  Ensure that we
have enough space in the unote to track the source properly.
> event: create a typedef for the unote ident type

- src/CMakeLists.txt
The DLLs are runtime components.  The Windows target installs the
runtime components into the bin directory, and the import libraries into
the lib directory.  This enables the runtime setup to be simplified on
Windows.
> build: install swiftDispatch.dll to bin

- src/shims/generic_sys_queue.h
This adjusts the `LIST_ENTRY` to define the structure correctly.  This
allows for the `LIST_REMOVE` and `LIST_INSERT_HEAD` macros to be defined
properly and set the fields previous pointers as well when updating the
list.  This is needed to enable the use of the macros for list
manipulations.  Found while implementing file sources for Windows.
> shims: correct list macros

- src/event/event_epoll.c
- tests/CMakeLists.txt
- tests/dispatch_io_pipe_close.c
This is just a combination of these two PRs combining authorship information:
#477 
#476 
As one can see #476 fails with ToT. Lets see if with 477 it passes and then lets land this sucker!
> Combined PR: SR-9033 handle EPOLLHUP

- src/internal.h
The [Nix Packages collection](https://nixos.org/) on Linux routinely builds with the fortify option (`-D_FORTIFY_SOURCE=2`). Currently, libdispatch fails to build with the following error:
```
/home/michael/swift/src/swift-corelibs-libdispatch/src/queue.c:47:2: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
_dispatch_client_assert_fail(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/michael/swift/src/swift-corelibs-libdispatch/src/internal.h:1056:3: note: expanded from macro '_dispatch_client_assert_fail'
asprintf(&_msg, "%s" fmt, DISPATCH_ASSERTION_FAILED_MESSAGE, \
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/sr4253np2gz2bpha4gn8gqlmiw604155-glibc-2.27-dev/include/bits/stdio2.h:199:3: note: expanded from …
```
> [SR-10559] libdispatch fails to build with _FORTIFY_SOURCE=2

- src/shims/generic_sys_queue.h
This fixes libdispatch on Windows where we use the shims rather than a
system provided `sys/queue.h` as that is a BSD extension.
> shims: correct `TAILQ_CONCAT`

- src/swift/Source.swift
Windows uses handles internally for the dispatch sources.  Convert the
`fileDescriptor` parameter on the incoming point to `HANDLE`s when
building the `DispatchSource`.  This fixes passing invalid parameters to
the Windows system functions.
> Swift: correct dispatch source construction on Win32

- src/CMakeLists.txt
Ensure that we link against the correct VC runtime libraries.
Additionally, enable the macros to indicate that we are linking against
the VC runtimes dynamically to get proper DLL storage.  This fixes
memory issues and file descriptor table synchrony.
> build: ensure that we link against the correct library

- src/event/event_epoll.c
- tests/CMakeLists.txt
- tests/dispatch_io_pipe_close.c
this is
git cherry-pick -x 33c5d81dc254526c1c1c7afedd1788be934e1814 ffc713358c72d1e0e1a2218f0eb6a7b8a6c73049
which backports #478 the fix for https://bugs.swift.org/browse/SR-9033 . CC @millenomi, this should make corelibs-foundation and the tests more stable.
> [5.0] Combined PR: SR-9033 handle EPOLLHUP #478

- tests/CMakeLists.txt
> dispatch_group and dispatch_starfish are failing sporadically in CI

- src/CMakeLists.txt
- cmake/modules/SwiftSupport.cmake prepends each flag with '-Xcc' but
if the flag evaluates to empty then an extra -Xcc is added to the
compiler options.
- Explicitly add the option with a conditional '-Xcc' before it as well.
- This fixes the "warning: argument unused during compilation: '-Xcc'"
seen in the error logs.
> When adding conditionally included compiler flags, dont use the CFLAGS section

- src/swift/IO.swift
- src/swift/Source.swift
This adds a new set of API overloads which provide an interface which
use the HANDLE rather than file descriptor.  This makes it easier to
create the dispatch sources without having to convert the file handle to
a file descriptor.
> swift: add a set of Windows extensions

- src/swift/Queue.swift
The typo fix at https://github.com/apple/swift-corelibs-libdispatch/commit/a33e4fd965eadd815c4a1b8e8ab80a4cd702d053#diff-8a1894abc995edb93f386d821287e44f did not add the colon after the parameter name.
> Fix formatting in documentation for "deadline" parameter.

- src/io.c
`_dispatch_operation_perform()` uses `_aligned_malloc()` on Windows to
allocate the data buffer. This means that we cannot use
`DISPATCH_DATA_DESTRUCTOR_FREE` when we create the `dispatch_data_t`.
Provide a custom destructor which correctly frees the buffer.
Discovered while porting the dispatch_io test to Windows.
> io: free Windows operation data with _aligned_free()

- src/shims/generic_sys_queue.h
This needs to set the `te_next` of the last element in `head1` and also
handle the case where `head1` is empty. This fixes a hang in the
dispatch_context_for_key test on Windows because the the queue-specific
list was getting corrupted in `_dispatch_queue_specific_head_dispose()`.
> shims: fix TAILQ_CONCAT() edge cases

- CMakeLists.txt
- src/CMakeLists.txt
- src/internal.h
- src/shims.h
- tests/CMakeLists.txt
Remove the libbsd dependency on Linux.  This simplifies the build for
Linux where sometimes we would get the wrong sys/queue.h instead.
> Remove libbsd dependency for Linux

- CMakeLists.txt
- src/CMakeLists.txt
- src/internal.h
- src/shims.h
- tests/CMakeLists.txt
Broke the Ubuntu 14.04 build (https://ci.swift.org/job/oss-swift-5.1-incremental-RA-linux-ubuntu-14_04/433/).
Reverts apple/swift-corelibs-libdispatch#492
> Revert "Remove libbsd dependency for Linux"

- CMakeLists.txt
- src/CMakeLists.txt
- src/internal.h
- src/shims.h
- tests/CMakeLists.txt
This reverts commit 4b87733f3e5e62a1c7a243d7e06cd35ae4b665b3.
> Revert "Revert "Remove libbsd dependency for Linux""

- src/CMakeLists.txt
- src/shims/generic_win_stubs.c
- src/shims/generic_win_stubs.h
- src/shims/time.h
`_dispatch_uptime()` and `_dispatch_monotonic_time()` are currently
using interrupt time APIs which return values cached by the scheduler.
This is causing the dispatch_after test to fail on Windows. Switch them
to the "Precise" APIs which incorporate a hardware time reading into
their results. Unfortunately, these functions are not exported by any
import libraries and we have to locate them at runtime.
Also, `_dispatch_monotonic_time()` should not be using the unbiased
version of the API because it is expected to include suspend time.
> shims: use the precise Windows time functions

- src/CMakeLists.txt
- src/io.c
- src/shims/generic_win_stubs.h
This function assumes POSIX-style paths. Add Windows-specific checks for
absolute paths and separators.
Additionally, `_dispatch_fd_entry_guarded_open()` does not handle the
open flags correctly. `O_RDONLY` is 0, so we need to use a switch
statement to check for it. `O_EXCL` is not handled at all. `O_TRUNC`'s
behavior needs to change depending on whether `O_CREAT` is specified.
Finally, we must open files with maximum sharing to match the semantics
of other platforms. (The dispatch_io test already has a handle open when
it calls `dispatch_io_create_with_path()`.)
> io: fix dispatch_io_create_with_path() on Windows

- tests/CMakeLists.txt
- tests/dispatch_io.c
- tests/dispatch_io_pipe_close.c
This lets us build and run the full extended test suite for Windows! I
caught several bugs in Dispatch's Windows port while I was working on
this and I submitted pull requests to fix them (#493, #494). The only
dispatch_io test case which fails right now is test_io_stop, and that's
because we don't have pipe support on Windows yet.
> tests: port dispatch_io and dispatch_io_pipe_close to Windows

- src/event/event_windows.c
- src/io.c
- src/shims/generic_win_stubs.c
- src/shims/generic_win_stubs.h
- tests/CMakeLists.txt
- tests/dispatch_io_pipe.c
- tests/dispatch_test.c
This implements full support for using pipe sources on Windows to
trigger an event when a pipe becomes readable or writable.
Due to differences between the Windows asynchronous I/O model and the
Unix model, this is rather complex. On Windows, the standard mechanism
to achieve asynchronous pipe I/O is to just read or write from the pipe
and then get notified once the operation completes. Unlike the Unix
`select()`/`poll()` model, there is no way to simply know when a pipe
becomes readable or writable without actually running an operation. So
we need to resort to several tricks in order to achieve the semantics
that Dispatch wants here.
To monitor a pipe for readability, we take advantage of the fact that a
zero-byte `ReadFile()` on a pipe will block until data becomes available
in the …
> event: support pipe sources on Windows

- src/internal.h
- tests/Foundation/bench.mm
- tests/dispatch_apply.c
- tests/dispatch_concur.c
- tests/dispatch_priority.c
- tests/dispatch_readsync.c
- tests/dispatch_vm.c
A warning has been added to sys/sysctl.h that is treated as an error when compiling; see https://patches-gcc.linaro.org/patch/19443/#34639 for the discussion. This patch adds a guard to prevent the file from being included when compiling on Linux.
> sys/sysctl.h is deprecated on Linux

- src/CMakeLists.txt
For reference, this is a build that fails: https://ci.swift.org/view/swift-master-next/job/oss-swift-incremental-RA-linux-ubuntu-16_04-master-next/11406/console
It repeatedly complains about "-momit-leaf-frame-pointer" being unused.
> Address TODO to unblock master-next.

- src/event/event_windows.c
- src/io.c
- src/shims/generic_win_stubs.c
- src/shims/generic_win_stubs.h
Provide an initial implementation of Windows socket sources using
WSAEventSelect(). This is sufficient for the dispatch_io_net test to
pass on Windows.
> event: support socket sources on Windows

- src/CMakeLists.txt
This adds support for a new variable `CMAKE_SWIFT_COMPILER_TARGET` which
mirror's CMake's `CMAKE_Swift_COMPILER_TARGET`.
> build: support `CMAKE_SWIFT_COMPILER_TARGET`

- src/shims/atomic.h
This generalises the path to always perform this substitution in C++
mode.  This should repair the build of libdispatch on android.
> shims: always replace `_Bool` with `bool` in C++

- src/event/event_windows.c
Currently, file sources are all registered with a global
`_dispatch_file_handles` list that has a lock around it. Remove this in
favor of posting muxnote pointers to the I/O completion port using the
same mechanism as the other source types.
> event: simplify the Windows file source implementation

- src/event/event_windows.c
- tests/CMakeLists.txt
- tests/dispatch_io_muxed.c
Implement the cases in `_dispatch_unote_register_muxed()` and
`_dispatch_unote_unregister_muxed()` for when multiple event sources are
open on a handle and we need to combine them.
The test suite doesn't hit these codepaths anywhere and we haven't run
into issues with Foundation yet, so I added a dispatch_io_muxed test
which opens multiple sources on a file/pipe/socket and checks that
events fire correctly.
> event: implement source muxing on Windows

- tests/dispatch_io_muxed.c
With this fix, all the tests pass again when built and run natively on Android, as Android has no global /tmp directory but [the Termux app that I'm using](https://github.com/termux/termux-app) sets TMPDIR, which is the usual variable for POSIX.
> tests: for Android, check TMPDIR first in dispatch_io_muxed

- CMakeLists.txt
- src/CMakeLists.txt
Adjust the output location of the generated executable content to the root of
the build tree.  This is needed primarily on Windows where there is no concept
of a RPATH, and the current directory is scanned for the dependent libraries.
> build: place executable content into the root of the build

- CMakeLists.txt
- src/BlocksRuntime/CMakeLists.txt
- src/CMakeLists.txt
This follows the CMake recommendations for the tree layout.  It makes it
easier to follow the build infrastructure, and prepares the tree for
migration to CMake 3.15 to enable Swift support.
> build: sink BlocksRuntime into its own directory

- CMakeLists.txt
- tests/dispatch_context_for_key.c
- tests/dispatch_data.c
- tests/dispatch_io_muxed.c
Use `CTest` module rather than the custom `ENABLE_TESTING` option.  The
inclusion of `CTest` will default `BUILD_TESTING` to true, which
preserves the existing behaviour.
> build: migrate to standard mechanism for testing

- tests/dispatch_select.c
The tests were using `test_double_less_than_or_equal` which raised a warning
when building on Linux-x86_64:
```
tests/dispatch_select.c:72:51: error: implicit conversion from 'ssize_t' (aka 'long') to 'double' may lose precision
tests/dispatch_select.c:131:61: error: implicit conversion from 'long' to 'double' may lose precision
```
Use `test_sizet_less_than_or_equal` instead.
> tests: correct the check function (NFCI)

- src/shims/hw_config.h
The Windows CPU detection code is not reporting the intended values.
`physical_cpus` should report the number of physical cores instead of
the number of packages, and `active_cpus` should report the number of
available logical cores instead of the number of available physical
cores. This fixes an issue where the `dispatch_apply` test times out on
hyperthreaded systems.
> hw_config: fix Windows CPU detection

- src/queue.c
The Windows thread pool implementation is calling `_beginthreadex` with
a stack size of 64 KB. This seems like a misunderstanding to me. In the
pthread code, `_dispatch_mgr_root_queue_init` does call
`pthread_attr_setstacksize` with a 64 KB size. However, this only
applies to the pthread root queue manager, and pthread root queues are
only supported on Apple platforms anyway.
We can confirm that using the OS default stack size is the intended
semantic by looking at the `dispatch_select` test, which expects to be
able to stack-allocate a 500 KB buffer in an event handler. This test is
failing on Windows because there is not enough stack space. We've also
run into various related issues in Swift which only happen on Windows,
and I suspect that this is just because the stack size isn't so …
> queue: use the default stack size on Windows

- dispatch/base.h
- src/event/event_epoll.c
- src/io.c
- src/semaphore.c
- src/shims/lock.c
- src/transform.c
Address `-Werror,-Wimplicit-fallthrough` as identified by clang.  This fixes a
couple of build warnings which are treated as errors.  NFC.
> semaphore: annotate fallthrough (NFC)

- tests/dispatch_timer_short.c
```
testes/dispatch_timer_short.c:58:74: error: implicit conversion from 'unsigned long long' to 'double' may loose precision [-Werror,-Wimplicit-int-float-conversion]
test_long_less_than("Frequency", 1, (long)ceil((double)delay/(finalCount*interval)));
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```
Fix the casting for `finalCount` and explicitly cast the result which would be
an `unsigned long long` due to the multiplication by `interval`.
> tests: fix -Werror,-Wimplicit-int-float-conversion

- src/swift/CMakeLists.txt
Some of the compiler and linker flags need to be used by dependent libraries
which requires making the flags public so that users of the libraries and the
export targets are setup properly.
> build: make some linkage flags public

- cmake/modules/DispatchCompilerWarnings.cmake
libdispatch will fail to build with a newly introduced clang diagnostic
`pointer-to-int-cast`. libdispatch converts a void pointer to a
dispatch_invoke_flags_t (aka unsigned int) in a few places. Ideally we would not
be doing this, but this solution at least gets libdispatch building again
with a newer version of clang.
> [build] Silence `-Wvoid-pointer-to-int-cast`

- tests/bsdtests.c
- tests/dispatch_io_muxed.c
- tests/dispatch_overcommit.c
These cause compile failures due to `-Werror -Wunused-result` when building on
NixOS. This PR upstreams patches need to package Swift on that OS.
> tests: Suppress unused return value warnings

- src/CMakeLists.txt
- src/swift/CMakeLists.txt
Remove the absolute path to the host stdlib for libswiftDispatch.so and add `$ORIGIN` to it and libdispatch.so.
Otherwise, you see the following in the current official release for linux:
```
> readelf -d swift-5.2.3-RELEASE-ubuntu18.04/usr/lib/swift/linux/lib*ispatch.so | ag "File:|runpath"
File: swift-5.2.3-RELEASE-ubuntu18.04/usr/lib/swift/linux/libdispatch.so
File: swift-5.2.3-RELEASE-ubuntu18.04/usr/lib/swift/linux/libswiftDispatch.so
0x000000000000001d (RUNPATH)            Library runpath: [/home/buildnode/jenkins/workspace/oss-swift-5.2-package-linux-ubuntu-18_04/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux]
```
> [CMake] fix runpath for ELF platforms

- src/queue.c
Use an auto-reset event for the dispatch queue on Windows.  On Linux,
`eventfd` is used, which is auto-reset unless `EFD_SEMAPHORE` is
specified.  This mirrors that behaviour.  The test suite continues to
pass after this change.
> dispatch: use auto-reset event for dispatch queue

- src/swift/IO.swift
- src/swift/Private.swift
- src/swift/Wrapper.swift
The `DispatchIO` constructor maps to `dispatch_io_create`.  The value on
Windows for the `fd` (which is actually a `HANDLE`) is being truncated
since `dispatch_fd_t` is actually `Int` not `Int32` on Windows.  Use the
`dispatch_fd_t` to ensure that the right size is always passed along.
> IO: match the signature for `DispatchIO` with `dispatch_io_create`

- dispatch/CMakeLists.txt
- dispatch/generic_static/module.modulemap
When compiling statically, we have to link against DispatchStubs in addition to the other dependencies, so we are defining a separate modulemap for that.
> Add modulemap for static compilation

- src/object.c
_dispatch_runloop_queue_xref_dispose is declared in src/queue_internal.h
but the declaration is hidden behind DISPATCH_COCOA_COMPAT. This means
the call to _dispatch_runloop_queue_xref_dispose must also be put behind
this preprocessor symbol.
> Add missing DISPATCH_COCOA_COMPAT preprocessor symbol.

- src/shims/hw_config.h
- src/transform.c
- tests/dispatch_apply.c
- tests/dispatch_io_net.c
- tests/dispatch_test.h
These changes include:
* hw_config.h: prevent referring to sysctlbyname on OpenBSD, as this
is not available on all platforms.
* transform.c: these stanzas referring to FreeBSD or Linux also apply
to OpenBSD.
* tests/dispatch_apply.c: stanza applying to Linux applies to OpenBSD
and also tweak style for consistency.
* tests/dispatch_io_net.c, tests/dispatch_test.h: stanzas applying to 
FreeBSD also apply to OpenBSD.
> Make some preliminary porting changes.

- dispatch/CMakeLists.txt
- dispatch/generic_static/module.modulemap
When compiling statically, we have to link against DispatchStubs in addition to the other dependencies, so we are defining a separate modulemap for that.
> [5.3] Add modulemap for static compilation

- src/CMakeLists.txt
- src/swift/CMakeLists.txt
Remove the absolute path to the host stdlib for libswiftDispatch.so and add $ORIGIN to it and libdispatch.so.
It has been suggested to me by some Swift devs that this would be good to get in before the 5.3 release, a cherry-pick from #541. @compnerd, I can remove the `$ORIGIN` portions and just make this about removing the toolchain stdlib rpath if you prefer.
This should be completely safe for the 5.3 branch, as it's just removing an unused rpath and adding rpaths that are already used, in a more explicit way.
> [5.3][CMake] fix runpath for ELF platforms

- src/shims/lock.h
There is a small typo in src/shims/lock.h.
Should read `transition` rather than `transiton`.
> docs: fix simple typo, transiton -> transition

- CMakeLists.txt
- tests/CMakeLists.txt
Android doesn't have a separate librt, it's just part of libc. Also, the static build wasn't working for armv7-a, because the test executables wouldn't link with the multiple definition errors listed in android/ndk#176, so use the workaround given there.
I didn't have any problems when cross-compiling for 64-bit arches, but hit the first one because I happen to have an i686 libc package installed in Ubuntu and the armv7 build would try to use librt.so from that. The second libunwind issue has been around for awhile, and I worked around it before [by not building the tests for libdispatch](https://github.com/buttaface/swift-android-sdk/blob/main/swift-android-531.patch#L123), but this gets them to build and run.
@compnerd, let me know what you think.
> [android] Put in fixes for librt and armv7-a

- src/shims/hw_config.h
The Windows 10 SDK Version 2104 (10.0.20348.0) which adds support for
Windows 11 introduces new enumerated values for the logical processor
configuration.  Only one of the two is documented at MSDN.
https://docs.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-logical_processor_relationship:
~~~
`RelationNumaNodeEx`
Introduced in TBD - Release Iron. Requests that the full affinity be
returned. Unlike the other relation types, `RelationNumaNodeEx` is not
used oninput. It is simply a request for `RelationNumaNode` with full
group information.
~~~
Treat this enumerated value as `RelationNodeNode`.  It is unclear what
the details of `RelationProcessorDie` is currently.  For now, we leave
that value ignored, though it is likely that we may have to address it
in the future once the value is …
> shims: adjust the Windows path for Windows 11

- src/BlocksRuntime/runtime.c
The rebranch branch is failing to build due to an unused refcount
variable in runtime.c. The variable is only used by an os_assert and
nowhere else. I've removed it and instead put the check directly in the
assert.
Failing build: https://ci.swift.org/view/Swift%20rebranch/job/oss-swift-rebranch-ubuntu-18_04/9/console
> Removing unused refcount variable

- src/shims/tsd.h
The Windows i686 builds expect this function to use the stdcall calling
convention.  The implementation correctly decorates the function to do
so.  However, the declaration did not match, which caused a build
failure on windows i686.
> shims: repair the build on Windows i686

- CMakeLists.txt
- src/shims/hw_config.h
The previous check did not work as the enumertors are not defines but
rather a proper enumerator.  This adds a build time check for the
support and conditionalises the compilation.
> shims: correct the check for newer SLPI enumerators

- CMakeLists.txt
- src/shims/hw_config.h
It seems that `RelationProcessorModule` is entirely undocumented but
listed as an enumerated value in the `LOGICAL_PROCESSOR_RELATIONSHIP`
enumeration.  Update for the 10.0.22000.0 SDK (Windows 11).
> shims: adjust the SLPI enumeration for Windows 11

- tests/bsdtestharness.c
- tests/dispatch_apply.c
There are build errors due to unused variables in two of the tests.
The build system builds these with `-Werror` so instead of a warning, it is a hard failure.
This is affecting the swift rebranch work, which has a newer clang that emits warnings in more cases, which is why we are seeing this now.
Failing build log:
https://ci.swift.org/view/Swift%20rebranch/job/oss-swift-rebranch-incremental-RA-linux-ubuntu-18_04/23/console
> Fix unused variable errors

- src/event/workqueue.c
- src/event/workqueue_internal.h
This enables workqueue monitoring on Windows to allow for overcommitting
threads if necessary.  We use a combination of WCT (wait chain tracing)
- to determine if there is an object being waited upon - and IO checking
- to determine if there is pending IO - to identify threads which are
executing workloads.  If no threads are executing workloads, then we may
be in a starvation state and will initialize new threads.  This should
fix the issue that has been previously reported with SPM hangs.
This is non-portable and ideally we would have an alternative approach
to tracking thread state, but this should at least unblock the current
situation.
> event: support workqueue monitoring on Windows

- src/shims/atomic.h
NDK 23 split `stdatomic.h` up and that causes problems when invoked from C++ files, so use the new `bits/stdatomic.h` instead as a workaround, as seen in the test for aosp-mirror/platform_bionic@76e2b15.
[Building libdispatch for Android with the new NDK causes linkage issues in the headers](https://github.com/buttaface/swift-android-sdk/runs/3402803617?check_suite_focus=true#step:7:889), so I used this same workaround that can be seen in the C++ test for that Bionic commit that split the header up and libdispatch builds for Android again.
I don't know if there's a better way to fix these linkage issues, so let me know if there is.
> [android] Update headers that were split in NDK 23

- dispatch/source.h
This cleans up a stray semicolon to allow building with `-Werror=c++98-compat-extra-semi` which is enabled by default in some versions of clang and produces an annoying number of diagnostics when building Swift.
> dispatch: remove stray semicolon (NFC

- src/event/workqueue.c
- src/event/workqueue_internal.h
This enables workqueue monitoring on Windows to allow for overcommitting
threads if necessary.  We use a combination of WCT (wait chain tracing)
- to determine if there is an object being waited upon - and IO checking
- to determine if there is pending IO - to identify threads which are
executing workloads.  If no threads are executing workloads, then we may
be in a starvation state and will initialize new threads.  This should
fix the issue that has been previously reported with SPM hangs.
This is non-portable and ideally we would have an alternative approach
to tracking thread state, but this should at least unblock the current
situation.
> [5.5] event: support workqueue monitoring on Windows

- src/shims/yield.c
Caused by `__builtin_arm_wfe()` sometimes causing a `SIGILL`.
For details please see https://bugs.swift.org/browse/SR-15166.
> Fix possible crash in _dispatch_wait_for_enqueuer on Android armeabi-v7a

- src/init.c
Builds fail on some linux systems, because none of the included headers imply that `<linux/limits.h>` was included.
> Add necessary #include for PATH_MAX on Linux

- src/swift/Block.swift
For some reason `numericCast` does not permit casting the flags value:
~~~
S:\SourceCache\swift-corelibs-libdispatch\src\swift\Block.swift:46:39: error: global function 'numericCast' requires that 'dispatch_block_flags_t' conform to 'BinaryInteger'
let flags: dispatch_block_flags_t = numericCast(flags.rawValue)
^
Swift.numericCast:1:24: note: where 'U' = 'dispatch_block_flags_t'
@inlinable public func numericCast<T, U>(_ x: T) -> U where T : BinaryInteger, U : BinaryInteger
^
S:\SourceCache\swift-corelibs-libdispatch\src\swift\Block.swift:46:39: note: did you mean to use '.rawValue'?
let flags: dispatch_block_flags_t = numericCast(flags.rawValue)
^
.rawValue
~~~
> swift: repair the Windows x86 build

- src/CMakeLists.txt
`_dispatch_preemption_yield(++spins)` expands to `(void)++spins;` on
various platforms. A recent Clang change updated the
`unused-but-set-variable` warning to skip counting operators as a use,
but it ignores `(void)`. Disable the error until that's fixed.
> Temporarily disable unused-but-set-variable until it's fixed in Clang

- src/CMakeLists.txt
- src/shims/yield.c
`_dispatch_preemption_yield(++spins)` has an expansion to
`(void)++spins`, but this isn't considered a use of `spins` in Clang.
Add a `(void)spins` to prevent an unused variable warning.
Resolves rdar://93596069.
> Prevent unused but set variable warning

- src/swift/Block.swift
`DISPATCH_ENUM` will use a typed enum which creates a typedef to an
elaborated type.  This fails to be imported into Swift as a numeric
type.  Explicitly convert the `numericCast`'ed value from the Swift
`OptionSet` to the `dispatch_block_flags_t` as a portable alternate
spelling.  This allows us to continue to import the enum as a typed
value.
Thanks to @beccadax for the pointer that this pattern may not work on
Darwin (which it does not!) and the suggestion for the explicit type
conversion!
> swift: remove Windows special case in `Block.swift`

- src/io.c
`libdispatch` depends on non-blocking writes to retry later. For pipes on Windows, we achieved this using `NtQueryInformationFile` to get the `WriteQuotaAvailable` for the pipe, but this function returns `0` when there is a blocking read on the receiver side (this appears to be an OS bug), which causes us to never proceed to the write.
This change rather sets `PIPE_NOWAIT` on the pipe's write handle, similar to what is done on other platforms. This call will fail if the pipe handle does not have `FILE_WRITE_ATTRIBUTES` set, which is not a problem with the typical case of using a `Foundation.Pipe`. If we cannot set `PIPE_NOWAIT`, we will proceed with blocking writes, which in some circumstances could lead to hangs.
This resolves an issue with `SourceKit-LSP` on Windows where tests and …
> Use PIPE_NOWAIT on Windows to avoid blocking on writes

- src/swift/Time.swift
We can mark `DispatchTimeInterval` as equatable because it already implements the equality check operator `==`.
This resolves an API disparity - on Darwin `DispatchTimeInterval` is already `Equatable`.
Doing this will allow `DispatchTimeInterval` to be used with a wide range of library functions which are defined to operate on `Equatable` objects. For example this is useful in tests when you might wish to use `XCTAssertEqual`.
Resolves https://github.com/apple/swift-corelibs-libdispatch/issues/669
> Mark DispatchTimeInterval Equatable

- tests/generic_win_port.c
My local Windows libdispatch build recently started failing due to a calling convention mismatch with the function we use as the `PINIT_ONCE_FN` argument of a `InitOnceExecuteOnce` invocation. The fix is to specify it explicitly.
> Fix build break due to calling convention mismatch on Windows

- .gitignore
- CMakeLists.txt
- dispatch/CMakeLists.txt
- dispatch/dispatch-vfs.yaml.in
- src/swift/CMakeLists.txt
Avoid polluting the build directory a small amount given that we can use `-fmodule-map-file=` for the C/C++ build of libdispatch.  Unfortunately, for the Swift build, we need to have the file copied over due to the umbrella header resolution.
Hopefully this reduces some of the race conditions that we have seen in the build.
Thanks to @dgregor for reminding me of the flag!
> build: slightly improve the build for libdispatch

- src/CMakeLists.txt
The `WaitChain*` functions require linking against AdvAPI32.
> build: add a link against AdvAPI32 on Windows

- src/shims/lock.c
This function is the initializer for the semaphore.  The seamphore storage itself may be stack allocated (or heap allocated) but without guarantee of 0-initialisation.  As a result, the subsequent CAS for the atomic replacement will fail silently, leaving the previously non-zero value in place, indicating that the value is a valid handle.  This would fail randomly and would ultimately result in a crash in the `CloseHandle` call associated with the clean up.
This issue was identified by SwiftLint on Windows.
> shims: fix a subtle bug in semaphore initialisation on Windows

- dispatch/CMakeLists.txt
There is a subtle difference between libdispatch built dynamically and statically: DispatchStubs.  We erroneously emit ObjC runtime calls into the build and the stubs provides a shim to provide a definition on non-ObjC runtime enabled targets.  When built dynamically, this is internalised and distributed as part of dispatch.dll/libdispatch.so, however when built statically, the consumer is responsible for linking against DispatchStubs.  The modulemap reflects this and we need to ensure that we correctly provide that modulemap.
Thanks to @MaxDesiatov for the help with debugging and testing a fix for this!
> dispatch: install the correct modulemap when building static

- .gitignore
- CMakeLists.txt
- dispatch/CMakeLists.txt
- dispatch/dispatch-vfs.yaml.in
- src/CMakeLists.txt
- src/shims/lock.c
- src/swift/CMakeLists.txt
- tests/generic_win_port.c
Backport a number of changes from main to the 5.9 release
- Windows fixes
* explicitly specify the callback calling convention to prevent a miscoompilation
* fix a semaphore initialisation issue on Windows
- Build Changes
* Use an overlay to use the correct modulemap for dispatch that allows us to avoid a build race condition and fix building dispatch with an installed copy of libdispatch
> Backport build and Windows fixes for 5.9

- src/io.c
#781 set the `PIPE_NOWAIT` flag on pipes in an attempt to get posix-like semantics. However, Windows will immediately return `0` from `WriteFile` if the *entire* write would not complete. This means that asking to write more bytes than the size of the pipe's buffer will never do anything. The same applies to asking to write more bytes than is left available in the buffer.
This change keeps #781's `PIPE_NOWAIT` and brings back some of its pipe buffer size checking logic, with the caveat to be careful with trusting `FILE_PIPE_LOCAL_INFORMATION.WriteQuotaAvailable` since we've seen it return 0 when a reader is blocked waiting on the other end of the pipe.
Fixes https://github.com/apple/sourcekit-lsp/issues/752
> Prevent infinite attempts to write to Win32 pipes 

- src/queue.c
On Windows, all threads that want to use Windows Runtime or COM components must be initialized with a call to [CoInitializeEx()](https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex) or the slightly more modern [RoInitialize()](https://docs.microsoft.com/en-us/windows/win32/api/roapi/nf-roapi-roinitialize) (same as `Windows::Foundation::Initialize`).
This change initializes all libdispatch threads so it’s possible to use COM and Windows Runtime APIs.
> [Win32] Initialize Windows Runtime on queue threads

- src/shims/yield.h
Fixes https://github.com/apple/swift-corelibs-libdispatch/issues/760
> Avoid using rand() that leads to a lock contention

- src/io.c
- tests/dispatch_io.c
- tests/dispatch_read2.c
aligned_alloc is more cleaner and portable.
> Prefer aligned_alloc over posix_memalign

- CMakeLists.txt
- cmake/modules/DispatchCompilerWarnings.cmake
- os/generic_win_base.h
- src/event/workqueue.c
- src/shims/generic_win_stubs.h
- tests/generic_win_port.c
- tests/generic_win_port.h
This patch consists of two commits:
- The first commit contains a minimal set of changes to make libdispatch compile on the MSYS2 environments.  There are slight differences in headers, which are accounted for, and the `-fms-extensions` variable is passed to clang to enable the `__popcnt64` intrinsic
- The second commit adds a GitHub actions job to validate the changes
If this project doesn't want to use GitHub actions, I can remove the second commit.
> Support compiling on MSYS2

- src/io.c
I'm _really_ confused about why this doesn't fail to compile on swift-ci; I would expect that `#else` branch to be tested when building for Linux. When I recently updated our internal copy of the Linux toolchain past https://github.com/apple/swift-corelibs-libdispatch/pull/805, it failed:
```
src/io.c:2377:59: error: expected ';' after expression
2377 |                         op->buf = aligned_alloc((size_t)PAGE_SIZE, op->buf_siz)
|                                                                                ^
|                                                                                ;
```
> Add a missing semicolon in src/io.c.

- src/swift/Queue.swift
- src/swift/Wrapper.swift
A few well known types like DispatchSemaphore, DispatchIO, DispatchGroup, DispatchQueue, DispatchSource should all be Sendable.
resolves rdar://123284763
> Adopt Sendable in DispatchQueue and similar types

- src/swift/Queue.swift
- src/swift/Wrapper.swift
**Description:** A few well known types like DispatchSemaphore, DispatchIO, DispatchGroup, DispatchQueue, DispatchSource should all be Sendable. This also adds a missing (as compared to Apple platforms) `@Sendable` to queue.async APIs.
**Risk:** Low, missing annotations.
**Review by:** @rokhinip 
**Testing:** CI testing
**Original PR:** https://github.com/apple/swift-corelibs-libdispatch/pull/821
**Radar:** rdar://123284763
> [6.0] Adopt Sendable in DispatchQueue and similar types

- CMakeLists.txt
- src/io.c
- tests/dispatch_io.c
- tests/dispatch_read2.c
This simply brings back #805 for platforms that need it.
> Keep posix_memalign() around for older Android APIs

- CMakeLists.txt
- src/io.c
- tests/dispatch_io.c
- tests/dispatch_read2.c
This was caught by thread sanitizer.
> Switching back _dispatch_operation_perform to use posix_memalign from aligned_malloc

- src/io.c
- tests/dispatch_io.c
- tests/dispatch_read2.c
This was caught by thread sanitizer.
> Switching back _dispatch_operation_perform to use posix_memalign from aligned_malloc for 6.0 release

- private/mach_private.h
Correct the comment DISPATCH_MACH_MSG_DESTRUCTOR_VM_DEALLOCATE at mach_private.h
> Correct the comment DISPATCH_MACH_MSG_DESTRUCTOR_VM_DEALLOCATE at mach_private.h

- cmake/modules/DispatchCompilerWarnings.cmake
Should fix this properly, but for now just disable the warning itself.
> Disable new `cast-function-type-mismatch`

- CMakeLists.txt
- src/BlocksRuntime/CMakeLists.txt
- src/CMakeLists.txt
We should use build IDs on Linux so that we can identify the built artefacts, and also so that we can match them up with debug information should we choose to separate it.
rdar://130582819
> [Linux] Enable build IDs.

- src/swift/Data.swift
`DispatchData.withUnsafeBytes` created a new `dispatch_data_t` by calling `dispatch_data_create_map`. I assume that the intention was that this memory was freed when `data` is destroyed, based on the presence of `_fixLifetime(data)` but `data` was just a plain `dispatch_data_t` C struct, that doesn’t have any cleanup operations associated with it when destroyed.
To fix the leak, wrap the `dispatch_data_t` in a `DispatchData`, which takes over the ownership of the `dispatch_data_t` and releases it when `data` gets destroyed.
Alternatively, `_fixLifetime` could have been replaced by `_swift_dispatch_release(unsafeBitCast(data, to: dispatch_object_t.self))` but I think using `DispatchData` is the cleaner solution.
----
For future reference, a minimal reproducer for this issue was
```swift …
```
> Fix a memory leak in `DispatchData.withUnsafeBytes`

- src/swift/Dispatch.swift
- src/swift/Queue.swift
These types are all trivially `Sendable`.
The lack of conformance has caused source compatibility failures in cross platform libraries, as shown in https://github.com/swiftlang/swift-source-compat-suite/pull/964#issuecomment-2606023518.
> Add missing `Sendable` conformances to `DispatchPredicate`, `DispatchQoS`, and `DispatchTimeoutResult`.

- cmake/config.h.in
`HAVE_STRLCPY` was added to the static configuration but not the dynamic configuration. Update the template for this.
> build: bring `config.h.in` into sync with checked in copy

- src/event/event_windows.c
- src/io.c
- tests/dispatch_io_pipe.c
Fixes https://github.com/swiftlang/swift-corelibs-libdispatch/issues/820 . There is a lot of useful context in this issue, which I will partially reproduce below.
I have an alternate PR that fixes this problem in a less fundamental way, but without a small requirements change to libdispatch which I describe below: https://github.com/swiftlang/swift-corelibs-libdispatch/pull/853.
Problem description, copied from the aforementioned PR:
> * In https://github.com/swiftlang/swift-corelibs-libdispatch/pull/781, the pipe was changed from `PIPE_WAIT` to `PIPE_NOWAIT` to achieve POSIX-like `O_NONBLOCK` semantics, as attempting to write a large buffer would cause the dispatch queue thread to block long enough to hit a time out.
> * The Windows pipe synchronization thread, …
> Switch Win32 pipes to PIPE_WAIT with sentinel bufsize

- src/event/event_windows.c
- src/io.c
- tests/dispatch_io_pipe.c
Cherry-pick changes from main to use a `PIPE_WAIT`-mode pipe on Windows. Additionally, steal a byte from the buffer to synchronise on as a sentinel byte to check if we are waiting on a client to read from the buffer.
> IO: switch Win32 pipes to `PIPE_WAIT` and use a sentinel byte

- CMakeLists.txt
There is no early swift-driver build for the Windows toolchain. As a result, libdispatch fails to build properly when CMP0157 is set to NEW due to object files not being generated.
This sets CMP0157 to OLD when targetting Android until the early swift-driver is available on Windows.
> Set CMP0157 to OLD for Android

- CMakeLists.txt
We can use the `CMAKE_Swift_USE_OLD_DRIVER` option to control the behaviour as the issue is related to the old Swift driver.
> build: simplify the handling for CMP0157

- dispatch/base.h
This change accomplishes two items:
1. splits out a new `DISPATCH_EXTERN` macro to decorate with `extern` or `extern "C"` based on the compilation mode (C vs C++).
2. enables a new configuration macro (`dispatch_STATIC`) that allows building with libdispatch for static linking. The default remains dynamic linking.
The motivation for `DISPATCH_EXTERN` is primarily being able to concisely define `DISPATCH_EXPORT`. This follows the naming scheme that most other Apple frameworks use (e.g. UIKit, Foundation, etc).
The change to introduce support for static linking is motivated by Windows. With the gradual roll out of static linking of the runtime, it would be convenient to be able to statically link dispatch into a fully sealed Swift program. Doing so requires building libdispatch without the …
> dispatch: split `DISPATCH_EXPORT` and prepare for static linking

- CMakeLists.txt
- cmake/modules/SwiftSupport.cmake
- src/swift/CMakeLists.txt
Migrating to using the nested swiftmodule structure. This avoids needing to compute the architecture in the CMake script, using the compiler to tell us what the triple should be, making the build more robust. This also means that we can drop the architecture-specific subdirectory and install the dispatch modules alongside the swiftmodules for the other projects.
Note: We will need changes to the Windows installer scripts to reflect the new layout.
> Install nested Swift modules

- tests/dispatch_apply.c
- tests/dispatch_workqueue.c
We need to use `pthread_getaffinity_np()` to get the active core count; using `sysconf()` will tell us about the underlying machine, which may have many more cores than the container in which we are executing.
rdar://152301793
> [Tests] Fix Dispatch tests to work in container environments.

- src/shims/lock.c
The `dispatch_sema4_timedwait` would reset the `_timeout` to an absolute time after the sleep was interrupted instead of when the sleep was called. Interrupting the process while it was sleeping would result in the new absolute timeout deadline being computed using the `timeout` offset from the time of the interrupt. e.g. if the timeout is 10 seconds, it will be ten seconds from when the process was interrupted because the absolute deadline was recomputed. Interrupting the process repeatedly while sleeping would will make the process go back to sleep instead of waking up when the original absolute deadline was reached.
`timeout` is a relative timeout offset. `nsec` and `_timeout` are absolute times since the epoch specifying when the wait should stop.
> POSIX: Keep original timeout from sleep call

- src/event/event_epoll.c
The error pops up when using the rebranch Clang (stable/20250402):
```
/home/build-user/swift-corelibs-libdispatch/src/event/event_epoll.c:92:27: error: implicit conversion changes signedness: 'int' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
92 |         return dmn->dmn_events & ~dmn->dmn_disarmed_events;
|                                ~ ^~~~~~~~~~~~~~~~~~~~~~~~~
```
> Silence signedness change through implicit conversion error

- src/event/event_windows.c
- src/io.c
- tests/dispatch_io_pipe.c
This change causes swift-package-manager to hang when using the swift-build backend.
`swift build --build-system swiftbuild`
https://github.com/swiftlang/swift-corelibs-libdispatch/issues/882
This reverts commit 1bf870dfbb305575978f2003174e9f6d83e0c83d, reversing changes made to 57a1f4e84c52bb5c8502767008a7ede5fc1504f7.
> Fixes:  #882  - Revert "Merge pull request #854 PIPE_WAIT"

- dispatch/base.h
- src/BlocksRuntime/CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
This adds the necessary build support required to build libdispatch and BlocksRuntime (libclosure) statically on Windows as well.
> build: adjust the build to support building statically on Windows

- src/CMakeLists.txt
When building against the static libdispatch, we need to inform the dispatch headers that the library will be linked statically via `-Ddispatch_STATIC`. Wire this up onto the dispatch library to allow `swiftDispatch` to properly propagate that flag.
> build: correct linking to static libdispatch on Windows

- src/event/event_windows.c
While it is sufficient to use the relaxed ordering for the acquire semantics in the `_dispatch_muxnote_retain`, we need to use the acquire release semantics on the release in `_dispatch_muxnote_release` to ensure that any pending retains are not interrupted. This should hopefully alleviate the occasional crashes that have been observed with the muxnote reference counting.
Fixes: #887, #844
> event: ensure acquire release semantics for muxnote disposal

- CMakeLists.txt
This is passed in separately for libswiftDispatch by `build-script`.
> build: Use new 16 KB page alignment on 64-bit Android

- CMakeLists.txt
__Explanation:__ Add a linker flag for the upcoming 16 KB page support in Android.
__Scope:__ Only affects Android
__Issue:__ None
__Original PR:__ #893
__Risk:__ None, only affects Android
__Testing:__ Passed trunk CI and confirmed locally that this fixed the alignment
__Reviewer:__ @compnerd
@swift-ci test
> [6.2] build: Use new 16 KB page alignment on 64-bit Android

- CMakeLists.txt
__Explanation:__ Add a linker flag for the upcoming 16 KB page support in Android.
__Scope:__ Only affects Android
__Issue:__ None
__Original PR:__ #893
__Risk:__ None, only affects Android
__Testing:__ Passed trunk and release/6.2 CI and confirmed locally that this fixed the alignment
__Reviewer:__ @compnerd
@swift-ci test
> [6.2.1] build: Use new 16 KB page alignment on 64-bit Android

- CMakeLists.txt
__Explanation:__ Add a linker flag for the upcoming 16 KB page support in Android.
__Scope:__ Only affects Android
__Issue:__ None
__Original PR:__ #893
__Risk:__ None, only affects Android
__Testing:__ Passed trunk and release/6.2 CI and confirmed locally that this fixed the alignment
__Reviewer:__ @compnerd
@swift-ci test
> [6.2.0] build: Use new 16 KB page alignment on 64-bit Android

- src/shims.h
- src/shims/hw_config.h
- tests/dispatch_workqueue.c
This improves the CPU core count handling for FreeBSD. This uses sysconf to grab the number of configured processors when logical and physical CPU counts are requested, and then pthread_getaffinity_np and the number of active processors. This takes into account the number of available cores when the process is restricted to a subset of the processors.
This also fixes the `dispatch_workqueye` test, which has its own implementation to extract the core count. FreeBSD does not have an `hw.activecpu` syscall, so the syscallbyname was failing and the activecpu count was garbage from the stack. I've updated the test to initialize the value with `0xa1a1a1` to make the garbage clearer. Also update the test for FreeBSD to take advantage of sysconf and pthread_getaffinity_np in the test.
Fixes: #897
> FreeBSD: Improve CPU core count handling
